In [65]:
from calendar import weekday
!pip install numpy matplotlib seaborn
!pip install scikit-learn

# Data manipulation
import pandas as pd
import numpy as np

# Vizualization
import matplotlib.pyplot as plt
import seaborn as sb

# Machine learning
from sklearn.model_selection import train_test_split
from sklearn.ensemble import RandomForestRegressor
from sklearn.metrics import mean_absolute_error, mean_squared_error, r2_score
from sklearn.preprocessing import LabelEncoder
from sklearn.model_selection import GridSearchCV

from mlxtend.frequent_patterns import apriori, association_rules
from mlxtend.preprocessing import TransactionEncoder
# Warnings
import warnings
warnings.filterwarnings('ignore')

Requirement already satisfied: numpy in ./venv/lib/python3.11/site-packages (2.2.1)
Requirement already satisfied: matplotlib in ./venv/lib/python3.11/site-packages (3.10.0)
Requirement already satisfied: seaborn in ./venv/lib/python3.11/site-packages (0.13.2)
Requirement already satisfied: contourpy>=1.0.1 in ./venv/lib/python3.11/site-packages (from matplotlib) (1.3.1)
Requirement already satisfied: cycler>=0.10 in ./venv/lib/python3.11/site-packages (from matplotlib) (0.12.1)
Requirement already satisfied: fonttools>=4.22.0 in ./venv/lib/python3.11/site-packages (from matplotlib) (4.55.3)
Requirement already satisfied: kiwisolver>=1.3.1 in ./venv/lib/python3.11/site-packages (from matplotlib) (1.4.7)
Requirement already satisfied: packaging>=20.0 in ./venv/lib/python3.11/site-packages (from matplotlib) (24.2)
Requirement already satisfied: pillow>=8 in ./venv/lib/python3.11/site-packages (from matplotlib) (11.0.0)
Requirement already satisfied: pyparsing>=2.3.1 in ./venv/lib/python3.11/site-packages (from matplotlib) (3.2.0)
Requirement already satisfied: python-dateutil>=2.7 in ./venv/lib/python3.11/site-packages (from matplotlib) (2.9.0.post0)
Requirement already satisfied: pandas>=1.2 in ./venv/lib/python3.11/site-packages (from seaborn) (2.2.3)
Requirement already satisfied: pytz>=2020.1 in ./venv/lib/python3.11/site-packages (from pandas>=1.2->seaborn) (2024.2)
Requirement already satisfied: tzdata>=2022.7 in ./venv/lib/python3.11/site-packages (from pandas>=1.2->seaborn) (2024.2)
Requirement already satisfied: six>=1.5 in ./venv/lib/python3.11/site-packages (from python-dateutil>=2.7->matplotlib) (1.17.0)
Requirement already satisfied: scikit-learn in ./venv/lib/python3.11/site-packages (1.6.0)
Requirement already satisfied: numpy>=1.19.5 in ./venv/lib/python3.11/site-packages (from scikit-learn) (2.2.1)
Requirement already satisfied: scipy>=1.6.0 in ./venv/lib/python3.11/site-packages (from scikit-learn) (1.14.1)
Requirement already satisfied: joblib>=1.2.0 in ./venv/lib/python3.11/site-packages (from scikit-learn) (1.4.2)
Requirement already satisfied: threadpoolctl>=3.1.0 in ./venv/lib/python3.11/site-packages (from scikit-learn) (3.5.0)

### Exploring the data

In [84]:
sales = pd.read_csv("superstore_final_dataset.csv")

In [67]:
sales.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 9800 entries, 0 to 9799
Data columns (total 18 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   Row_ID         9800 non-null   int64
 1   Order_ID       9800 non-null   object
 2   Order_Date     9800 non-null   object
 3   Ship_Date      9800 non-null   object
 4   Ship_Mode      9800 non-null   object
 5   Customer_ID    9800 non-null   object
 6   Customer_Name  9800 non-null   object
 7   Segment        9800 non-null   object
 8   Country        9800 non-null   object
 9   City           9800 non-null   object
 10  State          9800 non-null   object
 11  Postal_Code    9789 non-null   float64
 12  Region         9800 non-null   object
 13  Product_ID     9800 non-null   object
 14  Category       9800 non-null   object
 15  Sub_Category   9800 non-null   object
 16  Product_Name   9800 non-null   object
 17  Sales          9800 non-null   float64
dtypes: float64(2), int64(1), object(15)
memory usage: 1.3+ MB

In [5]:
# Lines and columns
sales.shape

(9800, 18)

In [6]:
sales.size

176400

In [7]:
sales

,Row_ID,Order_ID,Order_Date,Ship_Date,Ship_Mode,Customer_ID,Customer_Name,Segment,Country,City,State,Postal_Code,Region,Product_ID,Category,Sub_Category,Product_Name,Sales
0,1,CA-2017-152156,8/11/2017,11/11/2017,Second Class,CG-12520,Claire Gute,Consumer,United States,Henderson,Kentucky,42420.0,South,FUR-BO-10001798,Furniture,Bookcases,Bush Somerset Collection Bookcase,261.9600
1,2,CA-2017-152156,8/11/2017,11/11/2017,Second Class,CG-12520,Claire Gute,Consumer,United States,Henderson,Kentucky,42420.0,South,FUR-CH-10000454,Furniture,Chairs,"Hon Deluxe Fabric Upholstered Stacking Chairs,...",731.9400
2,3,CA-2017-138688,12/6/2017,16/06/2017,Second Class,DV-13045,Darrin Van Huff,Corporate,United States,Los Angeles,California,90036.0,West,OFF-LA-10000240,Office Supplies,Labels,Self-Adhesive Address Labels for Typewriters b...,14.6200
3,4,US-2016-108966,11/10/2016,18/10/2016,Standard Class,SO-20335,Sean O Donnel,Consumer,United States,Fort Lauderdale,Florida,33311.0,South,FUR-TA-10000577,Furniture,Tables,Bretford CR4500 Series Slim Rectangular Table,957.5775
4,5,US-2016-108966,11/10/2016,18/10/2016,Standard Class,SO-20335,Sean O Donnel,Consumer,United States,Fort Lauderdale,Florida,33311.0,South,OFF-ST-10000760,Office Supplies,Storage,Eldon Fold N Roll Cart System,22.3680
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
9795,9796,CA-2017-125920,21/05/2017,28/05/2017,Standard Class,SH-19975,Sally Hughsby,Corporate,United States,Chicago,Illinois,60610.0,Central,OFF-BI-10003429,Office Supplies,Binders,"Cardinal HOLDit! Binder Insert Strips,Extra St...",3.7980
9796,9797,CA-2016-128608,12/1/2016,17/01/2016,Standard Class,CS-12490,Cindy Schnelling,Corporate,United States,Toledo,Ohio,43615.0,East,OFF-AR-10001374,Office Supplies,Art,"BIC Brite Liner Highlighters, Chisel Tip",10.3680
9797,9798,CA-2016-128608,12/1/2016,17/01/2016,Standard Class,CS-12490,Cindy Schnelling,Corporate,United States,Toledo,Ohio,43615.0,East,TEC-PH-10004977,Technology,Phones,GE 30524EE4,235.1880
9798,9799,CA-2016-128608,12/1/2016,17/01/2016,Standard Class,CS-12490,Cindy Schnelling,Corporate,United States,Toledo,Ohio,43615.0,East,TEC-PH-10000912,Technology,Phones,Anker 24W Portable Micro USB Car Charger,26.3760
9799,9800,CA-2016-128608,12/1/2016,17/01/2016,Standard Class,CS-12490,Cindy Schnelling,Corporate,United States,Toledo,Ohio,43615.0,East,TEC-AC-10000487,Technology,Accessories,SanDisk Cruzer 4 GB USB Flash Drive,10.3840

In [8]:
# Checking for total null values
sales.isnull().sum()

Row_ID            0
Order_ID          0
Order_Date        0
Ship_Date         0
Ship_Mode         0
Customer_ID       0
Customer_Name     0
Segment           0
Country           0
City              0
State             0
Postal_Code      11
Region            0
Product_ID        0
Category          0
Sub_Category      0
Product_Name      0
Sales             0
dtype: int64

In [9]:
sales.dtypes

Row_ID             int64
Order_ID          object
Order_Date        object
Ship_Date         object
Ship_Mode         object
Customer_ID       object
Customer_Name     object
Segment           object
Country           object
City              object
State             object
Postal_Code      float64
Region            object
Product_ID        object
Category          object
Sub_Category      object
Product_Name      object
Sales            float64
dtype: object

In [10]:
sales.describe()

            Row_ID   Postal_Code         Sales
count  9800.000000   9789.000000   9800.000000
mean   4900.500000  55273.322403    230.769059
std    2829.160653  32041.223413    626.651875
min       1.000000   1040.000000      0.444000
25%    2450.750000  23223.000000     17.248000
50%    4900.500000  58103.000000     54.490000
75%    7350.250000  90008.000000    210.605000
max    9800.000000  99301.000000  22638.480000

### Data Cleaning

In [85]:
sales.drop(['Row_ID', 'Postal_Code'], axis=1, inplace = True)

In [42]:
sales.head()

,Order_ID,Order_Date,Ship_Date,Ship_Mode,Customer_ID,Customer_Name,Segment,Country,City,State,Region,Product_ID,Category,Sub_Category,Product_Name,Sales
0,CA-2017-152156,8/11/2017,11/11/2017,Second Class,CG-12520,Claire Gute,Consumer,United States,Henderson,Kentucky,South,FUR-BO-10001798,Furniture,Bookcases,Bush Somerset Collection Bookcase,261.9600
1,CA-2017-152156,8/11/2017,11/11/2017,Second Class,CG-12520,Claire Gute,Consumer,United States,Henderson,Kentucky,South,FUR-CH-10000454,Furniture,Chairs,"Hon Deluxe Fabric Upholstered Stacking Chairs,...",731.9400
2,CA-2017-138688,12/6/2017,16/06/2017,Second Class,DV-13045,Darrin Van Huff,Corporate,United States,Los Angeles,California,West,OFF-LA-10000240,Office Supplies,Labels,Self-Adhesive Address Labels for Typewriters b...,14.6200
3,US-2016-108966,11/10/2016,18/10/2016,Standard Class,SO-20335,Sean O Donnel,Consumer,United States,Fort Lauderdale,Florida,South,FUR-TA-10000577,Furniture,Tables,Bretford CR4500 Series Slim Rectangular Table,957.5775
4,US-2016-108966,11/10/2016,18/10/2016,Standard Class,SO-20335,Sean O Donnel,Consumer,United States,Fort Lauderdale,Florida,South,OFF-ST-10000760,Office Supplies,Storage,Eldon Fold N Roll Cart System,22.3680

In [13]:
sales.Country.value_counts()

Country
United States    9800
Name: count, dtype: int64

In [53]:
sales.Region.value_counts()

Region
West       3140
East       2785
Central    2277
South      1598
Name: count, dtype: int64

In [69]:
# Convert date columns
sales['Order_Date'] = pd.to_datetime(sales['Order_Date'], format='%d/%m/%Y')
sales['Ship_Date'] = pd.to_datetime(sales['Ship_Date'], format='%d/%m/%Y')

In [122]:
sales_sorted = sales.sort_values(by='Order_Date', ascending=True)
sales_sorted

,Order_ID,Order_Date,Ship_Date,Ship_Mode,Customer_ID,Customer_Name,Segment,Country,City,State,Region,Product_ID,Category,Sub_Category,Product_Name,Sales
7980,CA-2015-103800,2015-01-03,2015-01-07,Standard Class,DP-13000,Darren Powers,Consumer,United States,Houston,Texas,Central,OFF-PA-10000174,Office Supplies,Paper,"Message Book, Wirebound, Four 5 1/2 X 4 Forms/...",16.448
741,CA-2015-112326,2015-01-04,2015-01-08,Standard Class,PO-19195,Phillina Ober,Home Office,United States,Naperville,Illinois,Central,OFF-BI-10004094,Office Supplies,Binders,GBC Standard Plastic Binding Systems Combs,3.540
740,CA-2015-112326,2015-01-04,2015-01-08,Standard Class,PO-19195,Phillina Ober,Home Office,United States,Naperville,Illinois,Central,OFF-ST-10002743,Office Supplies,Storage,SAFCO Boltless Steel Shelving,272.736
739,CA-2015-112326,2015-01-04,2015-01-08,Standard Class,PO-19195,Phillina Ober,Home Office,United States,Naperville,Illinois,Central,OFF-LA-10003223,Office Supplies,Labels,Avery 508,11.784
1759,CA-2015-141817,2015-01-05,2015-01-12,Standard Class,MB-18085,Mick Brown,Consumer,United States,Philadelphia,Pennsylvania,East,OFF-AR-10003478,Office Supplies,Art,Avery Hi-Liter EverBold Pen Style Fluorescent ...,19.536
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1297,CA-2018-115427,2018-12-30,2019-01-03,Standard Class,EB-13975,Erica Bern,Corporate,United States,Fairfield,California,West,OFF-BI-10004632,Office Supplies,Binders,GBC Binding covers,20.720
906,CA-2018-143259,2018-12-30,2019-01-03,Standard Class,PO-18865,Patrick O Donnel,Consumer,United States,New York City,New York,East,FUR-BO-10003441,Furniture,Bookcases,"Bush Westfield Collection Bookcases, Fully Ass...",323.136
645,CA-2018-126221,2018-12-30,2019-01-05,Standard Class,CC-12430,Chuck Clark,Home Office,United States,Columbus,Indiana,Central,OFF-AP-10002457,Office Supplies,Appliances,Eureka The Boss Plus 12-Amp Hard Box Upright V...,209.300
908,CA-2018-143259,2018-12-30,2019-01-03,Standard Class,PO-18865,Patrick O Donnel,Consumer,United States,New York City,New York,East,OFF-BI-10003684,Office Supplies,Binders,Wilson Jones Legal Size Ring Binders,52.776
5091,CA-2018-156720,2018-12-30,2019-01-03,Standard Class,JM-15580,Jill Matthias,Consumer,United States,Loveland,Colorado,West,OFF-FA-10003472,Office Supplies,Fasteners,Bagged Rubber Bands,3.024

In [44]:
print(sales.info())

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 9800 entries, 0 to 9799
Data columns (total 16 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   Order_ID       9800 non-null   object
 1   Order_Date     9800 non-null   datetime64[ns]
 2   Ship_Date      9800 non-null   datetime64[ns]
 3   Ship_Mode      9800 non-null   object
 4   Customer_ID    9800 non-null   object
 5   Customer_Name  9800 non-null   object
 6   Segment        9800 non-null   object
 7   Country        9800 non-null   object
 8   City           9800 non-null   object
 9   State          9800 non-null   object
 10  Region         9800 non-null   object
 11  Product_ID     9800 non-null   object
 12  Category       9800 non-null   object
 13  Sub_Category   9800 non-null   object
 14  Product_Name   9800 non-null   object
 15  Sales          9800 non-null   float64
dtypes: datetime64[ns](2), float64(1), object(13)
memory usage: 1.2+ MB
None

### Feature Engineering

#### Add additional features

In [82]:
# Extract features from date column
sales['Order_Month'] = sales['Order_Date'].dt.month
sales['Order_Year'] = sales['Order_Date'].dt.year
sales['Order_Day'] = sales['Order_Date'].dt.day
sales['Order_Weekday'] = sales['Order_Date'].dt.weekday
sales['Quarter'] = sales['Order_Date'].dt.quarter

# Calculate shipping time (days)
sales['Shipping_Time'] = (sales['Ship_Date'] - sales['Order_Date']).dt.days

#

In [80]:
sales.Shipping_Time.value_counts()

Shipping_Time
4    2718
5    2147
2    1295
6    1170
3     978
7     615
0     514
1     363
Name: count, dtype: int64

In [86]:
sales.Ship_Mode.value_counts()

Ship_Mode
Standard Class    5859
Second Class      1902
First Class       1501
Same Day           538
Name: count, dtype: int64

In [10]:
sales.head()

,Order_ID,Order_Date,Ship_Date,Ship_Mode,Customer_ID,Customer_Name,Segment,Country,City,State,...,Category,Sub_Category,Product_Name,Sales,Order_Month,Order_Year,Order_Day,Order_Weekday,Quarter,Shipping_Time
0,CA-2017-152156,2017-11-08,2017-11-11,2,CG-12520,Claire Gute,0,United States,194,15,...,0,Bookcases,385,261.9600,11,2017,8,2,4,3
1,CA-2017-152156,2017-11-08,2017-11-11,2,CG-12520,Claire Gute,0,United States,194,15,...,0,Chairs,836,731.9400,11,2017,8,2,4,3
2,CA-2017-138688,2017-06-12,2017-06-16,2,DV-13045,Darrin Van Huff,1,United States,265,3,...,1,Labels,1430,14.6200,6,2017,12,0,2,4
3,US-2016-108966,2016-10-11,2016-10-18,3,SO-20335,Sean O Donnel,0,United States,153,8,...,0,Tables,366,957.5775,10,2016,11,1,4,7
4,US-2016-108966,2016-10-11,2016-10-18,3,SO-20335,Sean O Donnel,0,United States,153,8,...,1,Storage,571,22.3680,10,2016,11,1,4,7

#### Aggregate data by month

In [17]:

# Create 'month_year' in YYYY-MM format directly from the datetime column
sales['Month_Year'] = sales['Order_Date'].dt.strftime('%Y-%m')

# Aggregate sales by 'month_year'
monthly_sales = sales.groupby('Month_Year')['Sales'].sum().reset_index()

# Sort by 'month_year' to ensure proper calculation of lag and rolling features
monthly_sales = monthly_sales.sort_values('Month_Year').reset_index(drop=True)
monthly_sales['Month_Year'] = monthly_sales['Month_Year'].astype(str)
monthly_sales

   Month_Year        Sales
0     2015-01   14205.7070
1     2015-02    4519.8920
2     2015-03   55205.7970
3     2015-04   27906.8550
4     2015-05   23644.3030
5     2015-06   34322.9356
6     2015-07   33781.5430
7     2015-08   27117.5365
8     2015-09   81623.5268
9     2015-10   31453.3930
10    2015-11   77907.6607
11    2015-12   68167.0585
12    2016-01   18066.9576
13    2016-02   11951.4110
14    2016-03   32339.3184
15    2016-04   34154.4685
16    2016-05   29959.5305
17    2016-06   23599.3740
18    2016-07   28608.2590
19    2016-08   36818.3422
20    2016-09   63133.6060
21    2016-10   31011.7375
22    2016-11   75249.3995
23    2016-12   74543.6012
24    2017-01   18542.4910
25    2017-02   22978.8150
26    2017-03   51165.0590
27    2017-04   38679.7670
28    2017-05   56656.9080
29    2017-06   39724.4860
30    2017-07   38320.7830
31    2017-08   30542.2003
32    2017-09   69193.3909
33    2017-10   59583.0330
34    2017-11   79066.4958
35    2017-12   95739.1210
36    2018-01   43476.4740
37    2018-02   19920.9974
38    2018-03   58863.4128
39    2018-04   35541.9101
40    2018-05   43825.9822
41    2018-06   48190.7277
42    2018-07   44825.1040
43    2018-08   62837.8480
44    2018-09   86152.8880
45    2018-10   77448.1312
46    2018-11  117938.1550
47    2018-12   83030.3888

In [18]:
monthly_sales['Month_Year'].max()

'2018-12'

In [22]:
# Create a new column
sales['Month_Year'] = sales['Order_Date'].dt.to_period('M')

# Aggregate data
monthly_sales = sales.groupby('Month_Year').agg({'Sales': 'sum'}).reset_index()
monthly_sales

   Month_Year        Sales
0     2015-01   14205.7070
1     2015-02    4519.8920
2     2015-03   55205.7970
3     2015-04   27906.8550
4     2015-05   23644.3030
5     2015-06   34322.9356
6     2015-07   33781.5430
7     2015-08   27117.5365
8     2015-09   81623.5268
9     2015-10   31453.3930
10    2015-11   77907.6607
11    2015-12   68167.0585
12    2016-01   18066.9576
13    2016-02   11951.4110
14    2016-03   32339.3184
15    2016-04   34154.4685
16    2016-05   29959.5305
17    2016-06   23599.3740
18    2016-07   28608.2590
19    2016-08   36818.3422
20    2016-09   63133.6060
21    2016-10   31011.7375
22    2016-11   75249.3995
23    2016-12   74543.6012
24    2017-01   18542.4910
25    2017-02   22978.8150
26    2017-03   51165.0590
27    2017-04   38679.7670
28    2017-05   56656.9080
29    2017-06   39724.4860
30    2017-07   38320.7830
31    2017-08   30542.2003
32    2017-09   69193.3909
33    2017-10   59583.0330
34    2017-11   79066.4958
35    2017-12   95739.1210
36    2018-01   43476.4740
37    2018-02   19920.9974
38    2018-03   58863.4128
39    2018-04   35541.9101
40    2018-05   43825.9822
41    2018-06   48190.7277
42    2018-07   44825.1040
43    2018-08   62837.8480
44    2018-09   86152.8880
45    2018-10   77448.1312
46    2018-11  117938.1550
47    2018-12   83030.3888

#### Lag Features

In [15]:
monthly_sales['sales_lag_1'] = monthly_sales['Sales'].shift(1)
monthly_sales['sales_lag_2'] = monthly_sales['Sales'].shift(2)
monthly_sales['sales_lag_3'] = monthly_sales['Sales'].shift(3)

# Drop missing values if any
monthly_sales.head()

  Month_Year      Sales  sales_lag_1  sales_lag_2  sales_lag_3
0    2015-01  14205.707          NaN          NaN          NaN
1    2015-02   4519.892    14205.707          NaN          NaN
2    2015-03  55205.797     4519.892    14205.707          NaN
3    2015-04  27906.855    55205.797     4519.892    14205.707
4    2015-05  23644.303    27906.855    55205.797     4519.892

#### Rolling window features

In [16]:
# Rolling averages
monthly_sales['rolling_avg_3'] = monthly_sales['Sales'].rolling(window=3).mean()
monthly_sales['rolling_avg_6'] = monthly_sales['Sales'].rolling(window=6).mean()

# Drop missing values after rolling
monthly_sales = monthly_sales.dropna()
monthly_sales

,Month_Year,Sales,sales_lag_1,sales_lag_2,sales_lag_3,rolling_avg_3,rolling_avg_6
5,2015-06,34322.9356,23644.3030,27906.8550,55205.7970,28624.697867,26634.248267
6,2015-07,33781.5430,34322.9356,23644.3030,27906.8550,30582.927200,29896.887600
7,2015-08,27117.5365,33781.5430,34322.9356,23644.3030,31740.671700,33663.161683
8,2015-09,81623.5268,27117.5365,33781.5430,34322.9356,47507.535433,38066.116650
9,2015-10,31453.3930,81623.5268,27117.5365,33781.5430,46731.485433,38657.206317
10,2015-11,77907.6607,31453.3930,81623.5268,27117.5365,63661.526833,47701.099267
11,2015-12,68167.0585,77907.6607,31453.3930,81623.5268,59176.037400,53341.786417
12,2016-01,18066.9576,68167.0585,77907.6607,31453.3930,54713.892267,50722.688850
13,2016-02,11951.4110,18066.9576,68167.0585,77907.6607,32728.475700,48195.001267
14,2016-03,32339.3184,11951.4110,18066.9576,68167.0585,20785.895667,39980.966533
15,2016-04,34154.4685,32339.3184,11951.4110,18066.9576,26148.399300,40431.145783
16,2016-05,29959.5305,34154.4685,32339.3184,11951.4110,32151.105800,32439.790750
17,2016-06,23599.3740,29959.5305,34154.4685,32339.3184,29237.791000,25011.843333
18,2016-07,28608.2590,23599.3740,29959.5305,34154.4685,27389.054500,26768.726900
19,2016-08,36818.3422,28608.2590,23599.3740,29959.5305,29675.325067,30913.215433
20,2016-09,63133.6060,36818.3422,28608.2590,23599.3740,42853.402400,36045.596700
21,2016-10,31011.7375,63133.6060,36818.3422,28608.2590,43654.561900,35521.808200
22,2016-11,75249.3995,31011.7375,63133.6060,36818.3422,56464.914333,43070.119700
23,2016-12,74543.6012,75249.3995,31011.7375,63133.6060,60268.246067,51560.824233
24,2017-01,18542.4910,74543.6012,75249.3995,31011.7375,56111.830567,49883.196233
25,2017-02,22978.8150,18542.4910,74543.6012,75249.3995,38688.302400,47576.608367
26,2017-03,51165.0590,22978.8150,18542.4910,74543.6012,30895.455000,45581.850533
27,2017-04,38679.7670,51165.0590,22978.8150,18542.4910,37607.880333,46859.855450
28,2017-05,56656.9080,38679.7670,51165.0590,22978.8150,48833.911333,43761.106867
29,2017-06,39724.4860,56656.9080,38679.7670,51165.0590,45020.387000,37957.921000
30,2017-07,38320.7830,39724.4860,56656.9080,38679.7670,44900.725667,41254.303000
31,2017-08,30542.2003,38320.7830,39724.4860,56656.9080,36195.823100,42514.867217
32,2017-09,69193.3909,30542.2003,38320.7830,39724.4860,46018.791400,45519.589200
33,2017-10,59583.0330,69193.3909,30542.2003,38320.7830,53106.208067,49003.466867
34,2017-11,79066.4958,59583.0330,69193.3909,30542.2003,69280.973233,52738.398167
35,2017-12,95739.1210,79066.4958,59583.0330,69193.3909,78129.549933,62074.170667
36,2018-01,43476.4740,95739.1210,79066.4958,59583.0330,72760.696933,62933.452500
37,2018-02,19920.9974,43476.4740,95739.1210,79066.4958,53045.530800,61163.252017
38,2018-03,58863.4128,19920.9974,43476.4740,95739.1210,40753.628067,59441.589000
39,2018-04,35541.9101,58863.4128,19920.9974,43476.4740,38108.773433,55434.735183
40,2018-05,43825.9822,35541.9101,58863.4128,19920.9974,46077.101700,49561.316250
41,2018-06,48190.7277,43825.9822,35541.9101,58863.4128,42519.540000,41636.584033
42,2018-07,44825.1040,48190.7277,43825.9822,35541.9101,45613.937967,41861.355700
43,2018-08,62837.8480,44825.1040,48190.7277,43825.9822,51951.226567,49014.164133
44,2018-09,86152.8880,62837.8480,44825.1040,48190.7277,64605.280000,53562.410000
45,2018-10,77448.1312,86152.8880,62837.8480,44825.1040,75479.622400,60546.780183
46,2018-11,117938.1550,77448.1312,86152.8880,62837.8480,93846.391400,72898.808983
47,2018-12,83030.3888,117938.1550,77448.1312,86152.8880,92805.558333,78705.419167

In [25]:
monthly_sales.info()

<class 'pandas.core.frame.DataFrame'>
Index: 43 entries, 5 to 47
Data columns (total 7 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   Month_Year     43 non-null     period[M]
 1   Sales          43 non-null     float64
 2   sales_lag_1    43 non-null     float64
 3   sales_lag_2    43 non-null     float64
 4   sales_lag_3    43 non-null     float64
 5   rolling_avg_3  43 non-null     float64
 6   rolling_avg_6  43 non-null     float64
dtypes: float64(6), period[M](1)
memory usage: 2.7 KB

### Define Target and Features

In [26]:
# Separate target variable (Sales) from the predictors
target = 'Sales'
features = ['sales_lag_1', 'sales_lag_2', 'sales_lag_3', 'rolling_avg_3', 'rolling_avg_6']

X = monthly_sales[features]
y = monthly_sales[target]

### Split the data into training and testing sets

In [27]:
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, shuffle=False)

print(f"Training set: {X_train.shape}")
print(f"Testing set: {X_test.shape}")

Training set: (34, 5)
Testing set: (9, 5)

In [134]:
X_test

    sales_lag_1  sales_lag_2  sales_lag_3  rolling_avg_3  rolling_avg_6
39   10893.4448    6866.3374    5964.0320    8941.913433   16875.352683
40    9065.9581   10893.4448    6866.3374   12305.653700   14404.340917
41   16957.5582    9065.9581   10893.4448   15010.701000   11459.319533
42   19008.5867   16957.5582    9065.9581   15926.388967   12434.151200
43   11813.0220   19008.5867   16957.5582   15421.160900   13863.407300
44   15441.8740   11813.0220   19008.5867   18761.034000   16885.867500
45   29028.2060   15441.8740   11813.0220   22118.049400   19022.219183
46   21884.0682   29028.2060   15441.8740   29322.996400   22372.078650
47   37056.7150   21884.0682   29028.2060   30116.083333   24438.558667

In [28]:
y_test

39     35541.9101
40     43825.9822
41     48190.7277
42     44825.1040
43     62837.8480
44     86152.8880
45     77448.1312
46    117938.1550
47     83030.3888
Name: Sales, dtype: float64

### Train a Random Forest Regressor

In [95]:
# Initialize the model
rf_model = RandomForestRegressor(random_state=42, n_estimators=205, max_depth=3, min_samples_split=2)

# Train the model
rf_model.fit(X_train, y_train)

RandomForestRegressor(max_depth=3, n_estimators=205, random_state=42)

### Evaluate the Model

In [96]:
# Make predictions
y_pred = rf_model.predict(X_test)

# Evaluate performance

# MAE measures the average of the absolute differences between the predicted values and the actual values (in this case 128$ which is BAD)
mae = mean_absolute_error(y_test, y_pred)
# MSE
mse = mean_squared_error(y_test, y_pred)
# RMSE similar to MAE but gives more weight to larger errors
rmse = np.sqrt(mse)

print(f"Mean Absolute Error (MAE): {mae}")
print(f"Mean Squared Error (MSE): {mse}")
print(f"Root Mean Squared Error (RMSE): {rmse}")

Mean Absolute Error (MAE): 13100.263315730663
Mean Squared Error (MSE): 427701629.5839757
Root Mean Squared Error (RMSE): 20680.94846915817

#### Tune Hyperparameters

In [68]:
# Define parameter grid
param_grid = {
    'n_estimators': [200, 210, 220],
    'max_depth': [None, 3, 5],
    'min_samples_split': [2, 5, 7]
}

# Create GridSearchCV
grid_search = GridSearchCV(estimator=RandomForestRegressor(), param_grid=param_grid, cv=5)

# Fit grid search
grid_search.fit(X_train, y_train)

# Get the best parameters
best_params = grid_search.best_params_
print(f"Best Parameters: {best_params}")

Best Parameters: {'max_depth': None, 'min_samples_split': 2, 'n_estimators': 220}

### Future Predictions

In [102]:
# The most recent actual data
latest_actual_sales = monthly_sales.iloc[-1]['Sales']
latest_data = X_test.iloc[-1].copy()

# Replace lagged features
latest_data['sales_lag_1'] = latest_actual_sales
latest_data['sales_lag_2'] = monthly_sales.iloc[-2]['Sales']
latest_data['sales_lag_3'] = monthly_sales.iloc[-3]['Sales']
latest_data['rolling_avg_3'] = monthly_sales['Sales'][-3:].mean()
latest_data['rolling_avg_6'] = monthly_sales['Sales'][-6:].mean()
monthly_sales_copy = monthly_sales.copy()

# Empty list to store forecast values
forecast = []

# Forecast the next 3 months
for i in range(3):
    # predict the next month's sales
    predicted_sales = rf_model.predict(latest_data.values.reshape(1, -1))
    next_month = monthly_sales_copy['Month_Year'].max() + 1
    forecast.append({'Month_Year': next_month, 'Sales': predicted_sales})

    # append the forecasted data to the initial dataset
    new_row = pd.DataFrame({'Month_Year': [next_month], 'Sales': [predicted_sales]})
    monthly_sales_copy = pd.concat([monthly_sales_copy, new_row], ignore_index=True)

    # update tha lag features for the next month
    latest_data['sales_lag_3'] = latest_data['sales_lag_2']
    latest_data['sales_lag_2'] = latest_data['sales_lag_1']
    latest_data['sales_lag_1'] = predicted_sales

    # update the rolling window features
    latest_data['rolling_avg_3'] = monthly_sales_copy['Sales'][-3:].mean()
    latest_data['rolling_avg_6'] = monthly_sales_copy['Sales'][-6:].mean()

    # append the forecasted value to the test set for the next prediction
    # X_test = X_test.append(latest_data)
forecast_df = pd.DataFrame(forecast)
# Show the forecast for the next 3 months
print(f"Forecasted sales for the next 3 months: {forecast_df}")

Forecasted sales for the next 3 months:   Month_Year                Sales
0    2019-01  [63898.04109218573]
1    2019-02  [63017.35789532745]
2    2019-03  [68918.85610751422]

## Analiza danych

In [39]:
sales.info()

<class 'pandas.core.frame.DataFrame'>
DatetimeIndex: 9800 entries, 2017-11-08 to 2016-01-12
Data columns (total 15 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   Order_ID       9800 non-null   object
 1   Ship_Date      9800 non-null   datetime64[ns]
 2   Ship_Mode      9800 non-null   object
 3   Customer_ID    9800 non-null   object
 4   Customer_Name  9800 non-null   object
 5   Segment        9800 non-null   object
 6   Country        9800 non-null   object
 7   City           9800 non-null   object
 8   State          9800 non-null   object
 9   Region         9800 non-null   object
 10  Product_ID     9800 non-null   object
 11  Category       9800 non-null   object
 12  Sub_Category   9800 non-null   object
 13  Product_Name   9800 non-null   object
 14  Sales          9800 non-null   float64
dtypes: datetime64[ns](1), float64(1), object(13)
memory usage: 1.2+ MB

In [38]:
sales.head()

,Order_ID,Ship_Date,Ship_Mode,Customer_ID,Customer_Name,Segment,Country,City,State,Region,Product_ID,Category,Sub_Category,Product_Name,Sales
Order_Date,,,,,,,,,,,,,,,
2017-11-08,CA-2017-152156,2017-11-11,Second Class,CG-12520,Claire Gute,Consumer,United States,Henderson,Kentucky,South,FUR-BO-10001798,Furniture,Bookcases,Bush Somerset Collection Bookcase,261.9600
2017-11-08,CA-2017-152156,2017-11-11,Second Class,CG-12520,Claire Gute,Consumer,United States,Henderson,Kentucky,South,FUR-CH-10000454,Furniture,Chairs,"Hon Deluxe Fabric Upholstered Stacking Chairs,...",731.9400
2017-06-12,CA-2017-138688,2017-06-16,Second Class,DV-13045,Darrin Van Huff,Corporate,United States,Los Angeles,California,West,OFF-LA-10000240,Office Supplies,Labels,Self-Adhesive Address Labels for Typewriters b...,14.6200
2016-10-11,US-2016-108966,2016-10-18,Standard Class,SO-20335,Sean O Donnel,Consumer,United States,Fort Lauderdale,Florida,South,FUR-TA-10000577,Furniture,Tables,Bretford CR4500 Series Slim Rectangular Table,957.5775
2016-10-11,US-2016-108966,2016-10-18,Standard Class,SO-20335,Sean O Donnel,Consumer,United States,Fort Lauderdale,Florida,South,OFF-ST-10000760,Office Supplies,Storage,Eldon Fold N Roll Cart System,22.3680

#### Total sales by period

In [103]:
sales['Sales'].sum()

np.float64(2261536.7827000003)

In [24]:
start_date = '2015-01-01'
end_date = '2015-03-01'

# Filter rows that fall within the date range
filtered_sales = sales[(sales['Order_Date'] >= start_date) & (sales['Order_Date'] <= end_date)]

# Calculate the total sales within the date range
total_sales = filtered_sales['Sales'].sum()
total_sales

np.float64(20928.75)

#### Growth rate by period (Quarterly/Yearly)

In [82]:
sales.head()

,Order_ID,Order_Date,Ship_Date,Ship_Mode,Customer_ID,Customer_Name,Segment,Country,City,State,...,Category,Sub_Category,Product_Name,Sales,Order_Month,Order_Year,Order_Day,Order_Weekday,Quarter,Shipping_Time
0,CA-2017-152156,2017-11-08,2017-11-11,2,CG-12520,Claire Gute,0,United States,194,15,...,0,Bookcases,385,261.9600,11,2017,8,2,4,3
1,CA-2017-152156,2017-11-08,2017-11-11,2,CG-12520,Claire Gute,0,United States,194,15,...,0,Chairs,836,731.9400,11,2017,8,2,4,3
2,CA-2017-138688,2017-06-12,2017-06-16,2,DV-13045,Darrin Van Huff,1,United States,265,3,...,1,Labels,1430,14.6200,6,2017,12,0,2,4
3,US-2016-108966,2016-10-11,2016-10-18,3,SO-20335,Sean O Donnel,0,United States,153,8,...,0,Tables,366,957.5775,10,2016,11,1,4,7
4,US-2016-108966,2016-10-11,2016-10-18,3,SO-20335,Sean O Donnel,0,United States,153,8,...,1,Storage,571,22.3680,10,2016,11,1,4,7

In [86]:
quarterly_sales = sales.groupby(['Order_Year', 'Quarter'])['Sales'].sum().reset_index().sort_values(by=['Order_Year', 'Quarter']).reset_index(drop=True)
quarterly_sales

    Order_Year  Quarter        Sales
0         2015        1   73931.3960
1         2015        2   85874.0936
2         2015        3  142522.6063
3         2015        4  177528.1122
4         2016        1   62357.6870
5         2016        2   87713.3730
6         2016        3  128560.2072
7         2016        4  180804.7382
8         2017        1   92686.3650
9         2017        2  135061.1610
10        2017        3  138056.3742
11        2017        4  234388.6498
12        2018        1  122260.8842
13        2018        2  127558.6200
14        2018        3  193815.8400
15        2018        4  278416.6750

In [87]:
annual_sales = sales.groupby(['Order_Year'])['Sales'].sum().reset_index()
annual_sales = annual_sales.sort_values(by=['Order_Year']).reset_index(drop=True)
annual_sales

   Order_Year        Sales
0        2015  479856.2081
1        2016  459436.0054
2        2017  600192.5500
3        2018  722052.0192

In [97]:
q1_2015 = quarterly_sales[(quarterly_sales['Order_Year'] == 2015) & (quarterly_sales['Quarter'] == 1)]
q4_2015 = quarterly_sales[(quarterly_sales['Order_Year'] == 2015) & (quarterly_sales['Quarter'] == 4)]

qoq_growth = (q4_2015['Sales'].values[0] - q1_2015['Sales'].values[0]) / q1_2015['Sales'].values[0] * 100
print(f"QoQ Growth: {qoq_growth:.2f}%")

QoQ Growth: 140.13%

#### Most Selling Weekdays

In [98]:
weekday_sales = sales.groupby(['Order_Weekday'])['Sales'].sum().reset_index()
weekday_sales

   Order_Weekday        Sales
0              0  348791.5516
1              1  420535.9243
2              2  315888.9722
3              3  142839.2402
4              4  234710.8402
5              5  420901.4763
6              6  377868.7779

In [100]:
weekday_sales['Weekday_Name'] = weekday_sales['Order_Weekday'].map({0: 'Monday', 1: 'Tuesday', 2: 'Wednesday',
                                                              3: 'Thursday', 4: 'Friday', 5: 'Saturday',
                                                              6: 'Sunday'})
weekday_sales

   Order_Weekday        Sales Weekday_Name
0              0  348791.5516       Monday
1              1  420535.9243      Tuesday
2              2  315888.9722    Wednesday
3              3  142839.2402     Thursday
4              4  234710.8402       Friday
5              5  420901.4763     Saturday
6              6  377868.7779       Sunday

In [102]:
weekday_sales = weekday_sales.sort_values(by='Sales', ascending=False)
most_selling_weekday = weekday_sales.iloc[0]
most_selling_weekday

Order_Weekday              5
Sales            420901.4763
Weekday_Name        Saturday
Name: 5, dtype: object

In [118]:

sales.head()

,Order_ID,Order_Date,Ship_Date,Ship_Mode,Customer_ID,Customer_Name,Segment,Country,City,State,Region,Product_ID,Category,Sub_Category,Product_Name,Sales
0,CA-2017-152156,2017-11-08,2017-11-11,Second Class,CG-12520,Claire Gute,Consumer,United States,Henderson,Kentucky,South,FUR-BO-10001798,Furniture,Bookcases,Bush Somerset Collection Bookcase,261.9600
1,CA-2017-152156,2017-11-08,2017-11-11,Second Class,CG-12520,Claire Gute,Consumer,United States,Henderson,Kentucky,South,FUR-CH-10000454,Furniture,Chairs,"Hon Deluxe Fabric Upholstered Stacking Chairs,...",731.9400
2,CA-2017-138688,2017-06-12,2017-06-16,Second Class,DV-13045,Darrin Van Huff,Corporate,United States,Los Angeles,California,West,OFF-LA-10000240,Office Supplies,Labels,Self-Adhesive Address Labels for Typewriters b...,14.6200
3,US-2016-108966,2016-10-11,2016-10-18,Standard Class,SO-20335,Sean O Donnel,Consumer,United States,Fort Lauderdale,Florida,South,FUR-TA-10000577,Furniture,Tables,Bretford CR4500 Series Slim Rectangular Table,957.5775
4,US-2016-108966,2016-10-11,2016-10-18,Standard Class,SO-20335,Sean O Donnel,Consumer,United States,Fort Lauderdale,Florida,South,OFF-ST-10000760,Office Supplies,Storage,Eldon Fold N Roll Cart System,22.3680

In [129]:

daily_orders = sales.groupby('Order_Date')['Order_ID'].count().reset_index()
daily_orders

     Order_Date  Order_ID
0    2015-01-03         1
1    2015-01-04         3
2    2015-01-05         1
3    2015-01-06         9
4    2015-01-07         2
...         ...       ...
1225 2018-12-26         4
1226 2018-12-27         2
1227 2018-12-28        19
1228 2018-12-29        12
1229 2018-12-30         7

[1230 rows x 2 columns]

In [130]:
daily_orders = daily_orders.merge(sales[['Order_Date', 'Order_Weekday']].drop_duplicates(), on='Order_Date', how='left')

# Step 3: Group by Order_Weekday and sum the number of orders
weekday_orders = daily_orders.groupby('Order_Weekday')['Order_ID'].sum().reset_index()

# Step 4: Count the occurrences of each weekday in the dataset
weekday_count = daily_orders['Order_Weekday'].value_counts().sort_index()

# Step 5: Calculate the average number of orders per weekday
weekday_orders['Avg_Orders'] = weekday_orders['Order_ID'] / weekday_count

# Map Order_Weekday to Weekday Names (Optional)
weekday_orders['Weekday_Name'] = weekday_orders['Order_Weekday'].map({
    0: 'Monday', 1: 'Tuesday', 2: 'Wednesday', 3: 'Thursday', 4: 'Friday', 5: 'Saturday', 6: 'Sunday'
})

weekday_orders

   Order_Weekday  Order_ID  Avg_Orders Weekday_Name
0              0      1593    8.169231       Monday
1              1      1889    9.492462      Tuesday
2              2      1229    6.502646    Wednesday
3              3       541    4.434426     Thursday
4              4      1067    8.468254       Friday
5              5      1786    9.065990     Saturday
6              6      1695    8.391089       Sunday

#### Custumer Cohorts

In [7]:
candata = (sales[['Customer_ID', 'Order_Date']]
    .drop_duplicates()
    .assign(Year_Quarter=sales.Order_Date.dt.to_period(freq='Q'))
    .drop('Order_Date', axis=1)
    .drop_duplicates()
)

candata.head()

   Customer_ID Year_Quarter
0     CG-12520       2017Q4
2     DV-13045       2017Q2
3     SO-20335       2016Q4
5     BH-11710       2015Q2
12    AA-10480       2018Q2

In [8]:
cohorts = (
    candata.groupby('Customer_ID').min().rename(columns={'Year_Quarter' : 'Time_Cohort'})
)
cohorts.head()

            Time_Cohort
Customer_ID
AA-10315         2015Q1
AA-10375         2015Q2
AA-10480         2015Q2
AA-10645         2015Q2
AB-10015         2015Q1

In [9]:
cohorts_size = (
    cohorts
    .reset_index()
    .groupby('Time_Cohort')
    .size()
    .sort_index()
    .rename('Number_of_Customers')
)
cohorts_size

Time_Cohort
2015Q1    118
2015Q2    155
2015Q3    161
2015Q4    155
2016Q1     33
2016Q2     36
2016Q3     38
2016Q4     34
2017Q1     14
2017Q2     22
2017Q3      7
2017Q4      9
2018Q1      3
2018Q2      2
2018Q3      3
2018Q4      3
Freq: Q-DEC, Name: Number_of_Customers, dtype: int64

In [10]:
cohorts_size.info()

<class 'pandas.core.series.Series'>
PeriodIndex: 16 entries, 2015Q1 to 2018Q4
Freq: Q-DEC
Series name: Number_of_Customers
Non-Null Count  Dtype
--------------  -----
16 non-null     int64
dtypes: int64(1)
memory usage: 256.0 bytes

#### Mean and Total sales by customer Segment

In [25]:
# Total
total_sales_per_segment = sales.groupby('Segment')['Sales'].sum().reset_index()
total_sales_per_segment

       Segment        Sales
0     Consumer 1,148,060.53
1    Corporate   688,494.07
2  Home Office   424,982.18

In [30]:
# Mean
unique_orders_per_segment = sales.groupby('Segment')['Order_ID'].nunique().reset_index()
unique_orders_per_segment.columns = ['Segment', 'Unique_Order_Count']
segment_sales = pd.merge(unique_orders_per_segment, total_sales_per_segment, on='Segment')
segment_sales['Mean_Sales_Per_Order'] = segment_sales['Sales'] / segment_sales['Unique_Order_Count']
segment_sales

       Segment  Unique_Order_Count        Sales  Mean_Sales_Per_Order
0     Consumer                2537 1,148,060.53                452.53
1    Corporate                1491   688,494.07                461.77
2  Home Office                 894   424,982.18                475.37

#### Top Clients

In [34]:
top_clients = sales.groupby(['Customer_ID', 'Customer_Name', 'Segment']).agg(Sales=('Sales', 'sum'), Number_of_Orders=('Order_ID', 'nunique')).reset_index()
top_10_clients = top_clients.sort_values(by='Sales', ascending=False).head(10)
top_10_clients.reset_index(drop=True, inplace=True)
top_10_clients.index += 1
top_10_clients

   Customer_ID       Customer_Name      Segment     Sales  Number_of_Orders
1     SM-20320         Sean Miller  Home Office 25,043.05                 5
2     TC-20980        Tamara Chand    Corporate 19,052.22                 5
3     RB-19360        Raymond Buch     Consumer 15,117.34                 6
4     TA-21385        Tom Ashbrook  Home Office 14,595.62                 4
5     AB-10105       Adrian Barton     Consumer 14,473.57                10
6     KL-16645        Ken Lonsdale     Consumer 14,175.23                12
7     SC-20095        Sanjit Chand     Consumer 14,142.33                 9
8     HL-15040        Hunter Lopez     Consumer 12,873.30                 6
9     SE-20110        Sanjit Engle     Consumer 12,209.44                11
10    CC-12370  Christopher Conant     Consumer 12,129.07                 5

#### Repeat Customer Rate

In [35]:
first_purchase_data = sales[['Customer_ID', 'Order_Date']].drop_duplicates()
first_purchase_data['First_Purchase_Date'] = first_purchase_data.groupby('Customer_ID')['Order_Date'].transform('min')
first_purchase_data

     Customer_ID Order_Date First_Purchase_Date
0       CG-12520 2017-11-08          2016-10-15
2       DV-13045 2017-06-12          2017-06-12
3       SO-20335 2016-10-11          2016-10-11
5       BH-11710 2015-06-09          2015-06-09
12      AA-10480 2018-04-15          2015-05-04
...          ...        ...                 ...
9786    BG-11035 2015-11-05          2015-11-05
9787    CJ-12010 2018-03-27          2017-03-10
9791    KH-16360 2015-05-21          2015-04-29
9795    SH-19975 2017-05-21          2015-12-10
9796    CS-12490 2016-01-12          2016-01-12

[4905 rows x 3 columns]

In [36]:
customer_order_count = sales.groupby('Customer_ID')['Order_ID'].nunique()
customers_with_one_order = customer_order_count[customer_order_count == 1]
number_of_customers_with_one_order = customers_with_one_order.count()
number_of_customers_with_one_order

np.int64(13)

In [38]:
total_customers = sales['Customer_ID'].nunique()
total_customers

793

#### ABC Analysis (Customers)

In [7]:
customer_sales = sales.groupby(['Customer_ID', 'Customer_Name'])['Sales'].sum().reset_index()
customer_sales = customer_sales.sort_values(by='Sales', ascending=False)
customer_sales

    Customer_ID    Customer_Name      Sales
700    SM-20320      Sean Miller  25043.050
741    TC-20980     Tamara Chand  19052.218
621    RB-19360     Raymond Buch  15117.339
730    TA-21385     Tom Ashbrook  14595.620
6      AB-10105    Adrian Barton  14473.571
..          ...              ...        ...
508    MG-18205  Mitch Gastineau     16.739
145    CJ-11875     Carl Jackson     16.520
681    SC-20845       Sung Chung     14.112
456    LD-16855     Lela Donovan      5.304
760    TS-21085    Thais Sissman      4.833

[793 rows x 3 columns]

In [8]:
customer_sales['%_Contribution'] = (customer_sales['Sales'] / customer_sales['Sales'].sum()) * 100
customer_sales['Cumulative_%'] = customer_sales['%_Contribution'].cumsum()
customer_sales

    Customer_ID    Customer_Name      Sales  %_Contribution  Cumulative_%
700    SM-20320      Sean Miller  25043.050        1.107347      1.107347
741    TC-20980     Tamara Chand  19052.218        0.842446      1.949792
621    RB-19360     Raymond Buch  15117.339        0.668454      2.618246
730    TA-21385     Tom Ashbrook  14595.620        0.645385      3.263632
6      AB-10105    Adrian Barton  14473.571        0.639988      3.903620
..          ...              ...        ...             ...           ...
508    MG-18205  Mitch Gastineau     16.739        0.000740     99.998197
145    CJ-11875     Carl Jackson     16.520        0.000730     99.998928
681    SC-20845       Sung Chung     14.112        0.000624     99.999552
456    LD-16855     Lela Donovan      5.304        0.000235     99.999786
760    TS-21085    Thais Sissman      4.833        0.000214    100.000000

[793 rows x 5 columns]

In [9]:
def classify_customer(cumulative_percentage):
    if cumulative_percentage <= 80:
        return 'A'
    elif cumulative_percentage <= 95:
        return 'B'
    else:
        return 'C'

customer_sales['Customer_Category'] = customer_sales['Cumulative_%'].apply(classify_customer)
customer_sales

,Customer_ID,Customer_Name,Sales,%_Contribution,Cumulative_%,Customer_Category
700,SM-20320,Sean Miller,25043.050,1.107347,1.107347,A
741,TC-20980,Tamara Chand,19052.218,0.842446,1.949792,A
621,RB-19360,Raymond Buch,15117.339,0.668454,2.618246,A
730,TA-21385,Tom Ashbrook,14595.620,0.645385,3.263632,A
6,AB-10105,Adrian Barton,14473.571,0.639988,3.903620,A
...,...,...,...,...,...,...
508,MG-18205,Mitch Gastineau,16.739,0.000740,99.998197,C
145,CJ-11875,Carl Jackson,16.520,0.000730,99.998928,C
681,SC-20845,Sung Chung,14.112,0.000624,99.999552,C
456,LD-16855,Lela Donovan,5.304,0.000235,99.999786,C
760,TS-21085,Thais Sissman,4.833,0.000214,100.000000,C

In [10]:
category_totals = customer_sales.groupby('Customer_Category')['Sales'].sum().reset_index()
overall_total = category_totals['Sales'].sum()
category_totals['Percentage'] = (category_totals['Sales'] / overall_total) * 100
category_totals

  Customer_Category         Sales  Percentage
0                 A  1.807859e+06   79.939386
1                 B  3.396044e+05   15.016532
2                 C  1.140738e+05    5.044082

In [11]:
category_counts = customer_sales['Customer_Category'].value_counts()
category_counts

Customer_Category
A    392
B    209
C    192
Name: count, dtype: int64

#### Pareto Analysis for products

In [17]:
product_sales = sales.groupby('Product_Name')['Sales'].sum().reset_index()
product_sales = product_sales.sort_values(by='Sales', ascending=False)
product_sales

                                           Product_Name      Sales
403               Canon imageCLASS 2200 Advanced Copier  61599.824
648   Fellowes PB500 Electric Punch Plastic Comb Bin...  27453.384
443   Cisco TelePresence System EX90 Videoconferenci...  22638.480
783        HON 5400 Series Task Chairs for Big and Tall  21870.576
684          GBC DocuBind TL300 Electric Binding System  19823.479
...                                                 ...        ...
96                    Acme Serrated Blade Letter Opener      7.632
781                                 Grip Seal Envelopes      7.072
1792                                           Xerox 20      6.480
207                                             Avery 5      5.760
603   Eureka Disposable Bags for Sanitaire Vibra Gro...      1.624

[1849 rows x 2 columns]

In [32]:
product_sales['%_Contribution'] = (product_sales['Sales'] / product_sales['Sales'].sum()) * 100
product_sales['Cumulative_%'] = product_sales['%_Contribution'].cumsum()
top_20_percent_products = product_sales[product_sales['Cumulative_%'] <= 40]
top_20_percent_products

,Product_Name,Sales,%_Contribution,Cumulative_%
403,Canon imageCLASS 2200 Advanced Copier,61599.824,2.723804,2.723804
648,Fellowes PB500 Electric Punch Plastic Comb Bin...,27453.384,1.213926,3.937730
443,Cisco TelePresence System EX90 Videoconferenci...,22638.480,1.001022,4.938752
783,HON 5400 Series Task Chairs for Big and Tall,21870.576,0.967067,5.905819
684,GBC DocuBind TL300 Electric Binding System,19823.479,0.876549,6.782368
...,...,...,...,...
1415,Sanyo Counter Height Refrigerator with Crisper...,5906.520,0.261173,38.763306
755,Global Leather Executive Chair,5861.533,0.259184,39.022490
1197,"Office Impressions End Table, 20-1/2H x 24W x 20D",5801.816,0.256543,39.279033
1838,Zebra GX420t Direct Thermal/Thermal Transfer P...,5787.355,0.255904,39.534936
902,Iceberg Mobile Mega Data/Printer Cart,5751.774,0.254330,39.789267

In [28]:
unique_product_count = sales['Product_Name'].nunique()
unique_product_count

1849

In [25]:
product_sales = sales.groupby('Product_Name')['Sales'].sum().reset_index()
product_sales = product_sales.sort_values(by='Sales', ascending=False)
product_sales['%_Contribution'] = (product_sales['Sales'] / product_sales['Sales'].sum()) * 100
product_sales['Cumulative_%'] = product_sales['%_Contribution'].cumsum()
product_sales['Sales'].sum()

np.float64(2261536.7827000003)

####  Category performance

In [33]:
category_sales = sales.groupby('Category')['Sales'].sum().reset_index()
category_sales

          Category        Sales
0        Furniture  728658.5757
1  Office Supplies  705422.3340
2       Technology  827455.8730

In [37]:
subcategory_sales = sales.groupby(['Category', 'Sub_Category'])['Sales'].sum().reset_index()
subcategory_sales

           Category Sub_Category        Sales
0         Furniture    Bookcases  113813.1987
1         Furniture       Chairs  322822.7310
2         Furniture  Furnishings   89212.0180
3         Furniture       Tables  202810.6280
4   Office Supplies   Appliances  104618.4030
5   Office Supplies          Art   26705.4100
6   Office Supplies      Binders  200028.7850
7   Office Supplies    Envelopes   16128.0460
8   Office Supplies    Fasteners    3001.9600
9   Office Supplies       Labels   12347.7260
10  Office Supplies        Paper   76828.3040
11  Office Supplies      Storage  219343.3920
12  Office Supplies     Supplies   46420.3080
13       Technology  Accessories  164186.7000
14       Technology      Copiers  146248.0940
15       Technology     Machines  189238.6310
16       Technology       Phones  327782.4480

#### Cross-sell opportunities (Analiza koszykowa)

In [7]:
df_grouped = sales.groupby('Order_ID')['Product_ID'].apply(list).tolist()
df_grouped

[['TEC-PH-10002075'],
 ['FUR-TA-10003715', 'OFF-BI-10001597'],
 ['OFF-PA-10000176'],
 ['OFF-BI-10000343'],
 ['OFF-FA-10000611', 'OFF-PA-10004733'],
 ['OFF-PA-10001471'],
 ['OFF-AR-10001868', 'FUR-CH-10002602', 'OFF-EN-10000056', 'TEC-AC-10000474'],
 ['TEC-AC-10001314', 'FUR-FU-10002268'],
 ['OFF-AR-10000380', 'OFF-LA-10003930', 'OFF-PA-10001815', 'OFF-PA-10004082'],
 ['OFF-LA-10001982'],
 ['TEC-PH-10004922'],
 ['TEC-PH-10003273'],
 ['OFF-AR-10004511', 'TEC-PH-10001425', 'OFF-ST-10001490'],
 ['OFF-ST-10003479', 'FUR-TA-10004607', 'OFF-AR-10001022'],
 ['OFF-PA-10000357'],
 ['OFF-AP-10004249'],
 ['OFF-ST-10004950'],
 ['OFF-PA-10002986'],
 ['OFF-BI-10003984'],
 ['OFF-ST-10000532'],
 ['OFF-AR-10002257'],
 ['FUR-FU-10000409'],
 ['TEC-MA-10000029'],
 ['FUR-FU-10003773', 'OFF-PA-10001363', 'OFF-AR-10004757', 'OFF-BI-10000309'],
 ['TEC-PH-10000169', 'FUR-CH-10004675'],
 ['OFF-BI-10001097'],
 ['OFF-PA-10003591'],
 ['OFF-BI-10004140',
  'OFF-SU-10002301',
  'OFF-SU-10000646',
  'FUR-BO-10001337',
  'OFF-ST-10003442'],
 ['OFF-PA-10004092'],
 ['OFF-LA-10002475'],
 ['TEC-PH-10002923', 'OFF-PA-10004359', 'OFF-ST-10001511', 'OFF-AR-10002833'],
 ['FUR-CH-10001714'],
 ['OFF-LA-10003923', 'TEC-PH-10001051'],
 ['OFF-PA-10001804'],
 ['FUR-FU-10000747', 'FUR-FU-10001918', 'OFF-PA-10003309', 'OFF-PA-10001977'],
 ['OFF-FA-10003021', 'OFF-AR-10000634', 'OFF-LA-10001771', 'TEC-PH-10004434'],
 ['OFF-PA-10000788', 'TEC-AC-10002134', 'FUR-FU-10002456', 'TEC-PH-10002549'],
 ['OFF-AR-10004757',
  'TEC-PH-10001615',
  'OFF-PA-10003349',
  'OFF-AR-10000127',
  'OFF-SU-10002881'],
 ['TEC-AC-10001314'],
 ['FUR-FU-10004586'],
 ['OFF-LA-10003720', 'OFF-BI-10004600'],
 ['OFF-ST-10002574'],
 ['FUR-FU-10004091'],
 ['OFF-PA-10004353', 'TEC-PH-10001817', 'OFF-SU-10004737', 'FUR-CH-10002320'],
 ['FUR-FU-10001591', 'OFF-BI-10001787', 'FUR-FU-10003192'],
 ['FUR-FU-10001731', 'OFF-PA-10002160', 'OFF-PA-10002659'],
 ['TEC-AC-10003628'],
 ['TEC-PH-10002885'],
 ['OFF-PA-10003309'],
 ['OFF-BI-10004233', 'TEC-PH-10003505', 'OFF-AP-10001005', 'OFF-PA-10001712'],
 ['TEC-PH-10001128', 'TEC-PH-10004667', 'OFF-BI-10004817', 'OFF-BI-10004140'],
 ['OFF-PA-10001622'],
 ['OFF-EN-10004007'],
 ['TEC-PH-10000895'],
 ['OFF-BI-10002429'],
 ['OFF-LA-10004425', 'OFF-BI-10000320'],
 ['OFF-PA-10000174'],
 ['TEC-AC-10000199', 'OFF-PA-10002195'],
 ['TEC-AC-10001465', 'TEC-PH-10002597', 'FUR-FU-10000723'],
 ['OFF-ST-10004963', 'OFF-ST-10000943', 'FUR-FU-10004671', 'OFF-BI-10002735'],
 ['TEC-PH-10004667',
  'OFF-LA-10000443',
  'OFF-ST-10000918',
  'OFF-BI-10001196',
  'FUR-FU-10003981',
  'FUR-FU-10002508',
  'TEC-AC-10002647'],
 ['FUR-FU-10000771', 'TEC-AC-10002399', 'OFF-PA-10004983', 'OFF-ST-10004258'],
 ['FUR-CH-10004063'],
 ['OFF-ST-10004337', 'FUR-TA-10001039', 'TEC-AC-10000109'],
 ['TEC-MA-10000423'],
 ['OFF-BI-10001658', 'FUR-FU-10000246'],
 ['OFF-AR-10000390', 'OFF-ST-10000934', 'FUR-CH-10002780', 'FUR-CH-10004495'],
 ['OFF-EN-10004955',
  'TEC-PH-10002468',
  'TEC-PH-10000576',
  'OFF-BI-10002160',
  'TEC-AC-10003628'],
 ['OFF-ST-10000777'],
 ['OFF-AR-10003514'],
 ['OFF-BI-10003676'],
 ['OFF-PA-10003016'],
 ['OFF-PA-10003845'],
 ['TEC-PH-10000675',
  'OFF-BI-10000050',
  'FUR-TA-10004154',
  'TEC-AC-10002718',
  'OFF-AR-10003179'],
 ['OFF-LA-10001641'],
 ['OFF-SU-10001225', 'OFF-LA-10002043', 'FUR-BO-10000330'],
 ['OFF-AR-10003156', 'FUR-CH-10000988'],
 ['OFF-BI-10001765'],
 ['FUR-FU-10004864', 'OFF-BI-10003708'],
 ['FUR-TA-10002958'],
 ['OFF-BI-10003684'],
 ['OFF-ST-10004186'],
 ['TEC-PH-10000560', 'FUR-CH-10000847'],
 ['OFF-AR-10002399'],
 ['FUR-TA-10002041'],
 ['OFF-SU-10002189', 'FUR-FU-10001852'],
 ['OFF-AR-10002671', 'TEC-PH-10002726'],
 ['OFF-FA-10002975',
  'OFF-ST-10003996',
  'OFF-BI-10002571',
  'OFF-PA-10000477',
  'OFF-BI-10004209',
  'OFF-ST-10001963',
  'FUR-CH-10003833',
  'TEC-AC-10004568',
  'OFF-AR-10001419'],
 ['OFF-ST-10000585'],
 ['OFF-BI-10002799'],
 ['OFF-ST-10001496'],
 ['OFF-ST-10002444', 'TEC-AC-10001267'],
 ['FUR-FU-10004306'],
 ['TEC-AC-10000844'],
 ['OFF-BI-10001670'],
 ['OFF-ST-10001321'],
 ['OFF-BI-10004230', 'OFF-PA-10000350'],
 ['OFF-BI-10001982', 'OFF-BI-10004141', 'OFF-BI-10002103'],
 ['OFF-LA-10001569', 'FUR-FU-10004018'],
 ['OFF-EN-10001990', 'OFF-PA-10000587'],
 ['OFF-EN-10001099'],
 ['TEC-PH-10002923', 'OFF-AR-10000716'],
 ['OFF-PA-10000466'],
 ['TEC-AC-10000710'],
 ['TEC-PH-10001336'],
 ['FUR-CH-10001394', 'OFF-ST-10000798'],
 ['OFF-AR-10003045', 'FUR-CH-10000454', 'OFF-AR-10000380', 'OFF-ST-10000736'],
 ['FUR-FU-10004586', 'OFF-BI-10001116'],
 ['OFF-BI-10003876', 'OFF-ST-10003470'],
 ['OFF-BI-10001196'],
 ['OFF-PA-10001838',
  'OFF-FA-10000735',
  'TEC-PH-10001760',
  'OFF-EN-10004846',
  'OFF-SU-10003567',
  'TEC-PH-10001557',
  'TEC-AC-10003038'],
 ['OFF-PA-10000029', 'FUR-FU-10002116'],
 ['FUR-TA-10003954'],
 ['OFF-PA-10000788'],
 ['OFF-BI-10003876'],
 ['OFF-AR-10004010', 'OFF-EN-10004030', 'TEC-AC-10003023'],
 ['OFF-PA-10000312', 'OFF-AP-10004708'],
 ['OFF-LA-10004409'],
 ['FUR-FU-10000320'],
 ['OFF-AR-10001374'],
 ['FUR-CH-10000422'],
 ['OFF-BI-10002854'],
 ['TEC-AC-10001284', 'FUR-FU-10000221'],
 ['OFF-ST-10001932'],
 ['OFF-BI-10004716', 'TEC-AC-10002842'],
 ['TEC-PH-10004100'],
 ['TEC-PH-10003691', 'FUR-FU-10002878'],
 ['OFF-AR-10004999'],
 ['OFF-SU-10004290', 'OFF-PA-10000174', 'OFF-BI-10004308'],
 ['OFF-PA-10001804', 'OFF-ST-10000036'],
 ['FUR-FU-10002759'],
 ['TEC-PH-10002468', 'OFF-AR-10004165'],
 ['FUR-FU-10000521'],
 ['TEC-PH-10004531'],
 ['OFF-ST-10000107', 'TEC-PH-10000439'],
 ['FUR-CH-10001146'],
 ['OFF-LA-10003923'],
 ['OFF-ST-10001522', 'TEC-PH-10002352', 'FUR-CH-10003774'],
 ['OFF-LA-10000262'],
 ['OFF-ST-10000876', 'TEC-PH-10000586', 'TEC-AC-10003399'],
 ['OFF-ST-10000642'],
 ['OFF-PA-10003936', 'OFF-PA-10004530'],
 ['FUR-FU-10000550',
  'OFF-PA-10000528',
  'TEC-MA-10003183',
  'OFF-BI-10003305',
  'TEC-PH-10001425',
  'OFF-LA-10001474',
  'FUR-FU-10000672'],
 ['TEC-MA-10002859', 'OFF-AR-10002375', 'OFF-AR-10000657', 'OFF-FA-10000134'],
 ['OFF-BI-10001072', 'OFF-AR-10002135'],
 ['OFF-BI-10004593', 'OFF-BI-10002827'],
 ['OFF-AR-10000034', 'TEC-AC-10000290'],
 ['FUR-BO-10002916'],
 ['FUR-FU-10004091',
  'FUR-CH-10001891',
  'FUR-FU-10002918',
  'OFF-BI-10004593',
  'OFF-FA-10004854'],
 ['OFF-PA-10000595', 'OFF-BI-10000829', 'OFF-FA-10002676', 'TEC-AC-10000844'],
 ['OFF-BI-10000174'],
 ['OFF-PA-10001878'],
 ['FUR-BO-10004218'],
 ['OFF-AR-10001725', 'OFF-FA-10000840'],
 ['OFF-BI-10004364', 'OFF-PA-10000474'],
 ['OFF-BI-10001308', 'OFF-ST-10000046'],
 ['TEC-AC-10003628', 'FUR-BO-10003272', 'OFF-BI-10000050'],
 ['OFF-LA-10003223', 'OFF-ST-10002743', 'OFF-BI-10004094'],
 ['OFF-BI-10003529'],
 ['OFF-BI-10000591'],
 ['FUR-FU-10004006'],
 ['OFF-EN-10001453'],
 ['OFF-FA-10002763'],
 ['OFF-PA-10001947'],
 ['OFF-BI-10002609', 'FUR-BO-10004218', 'OFF-AR-10003251', 'OFF-PA-10002365'],
 ['FUR-FU-10004270', 'OFF-ST-10000617', 'FUR-FU-10001706'],
 ['OFF-ST-10001809', 'OFF-EN-10003845'],
 ['OFF-AP-10004532', 'FUR-FU-10001986'],
 ['OFF-PA-10001457'],
 ['FUR-CH-10002439', 'OFF-PA-10003063'],
 ['FUR-CH-10004698'],
 ['FUR-CH-10000863', 'OFF-PA-10003036'],
 ['OFF-PA-10004071'],
 ['OFF-EN-10003286', 'OFF-AR-10003772', 'OFF-BI-10002852'],
 ['OFF-BI-10004654'],
 ['OFF-LA-10004559', 'OFF-BI-10003291', 'OFF-ST-10001505'],
 ['FUR-BO-10004467', 'OFF-AR-10000716'],
 ['FUR-FU-10001468',
  'OFF-BI-10003684',
  'OFF-ST-10003716',
  'TEC-AC-10001101',
  'TEC-AC-10004864'],
 ['OFF-LA-10000240', 'FUR-FU-10002107'],
 ['FUR-CH-10001797', 'OFF-PA-10000246', 'OFF-BI-10001359'],
 ['FUR-FU-10000277'],
 ['TEC-AC-10002800'],
 ['OFF-BI-10001617',
  'OFF-ST-10000736',
  'TEC-AC-10004877',
  'OFF-ST-10003221',
  'OFF-BI-10003007'],
 ['FUR-TA-10001676', 'OFF-AP-10002350'],
 ['OFF-AR-10003631'],
 ['OFF-AP-10002578', 'TEC-AC-10000710', 'TEC-PH-10000984', 'OFF-PA-10000213'],
 ['OFF-AP-10003971'],
 ['FUR-CH-10004626'],
 ['OFF-AP-10001634', 'TEC-AC-10002370', 'OFF-PA-10000174'],
 ['FUR-BO-10003966'],
 ['OFF-FA-10000621', 'OFF-EN-10002600', 'OFF-PA-10004965', 'OFF-EN-10002504'],
 ['OFF-BI-10001107'],
 ['TEC-AC-10000023'],
 ['FUR-FU-10001095', 'TEC-PH-10004614', 'OFF-BI-10001575', 'OFF-LA-10001074'],
 ['FUR-FU-10001487',
  'OFF-AR-10002833',
  'TEC-PH-10002275',
  'OFF-BI-10003910',
  'OFF-AP-10002892',
  'FUR-TA-10001539',
  'TEC-PH-10002033'],
 ['TEC-PH-10001615', 'OFF-ST-10003208'],
 ['OFF-AR-10004757'],
 ['TEC-AC-10003709', 'OFF-FA-10000304'],
 ['FUR-CH-10000553', 'OFF-LA-10002762', 'FUR-FU-10000719'],
 ['OFF-ST-10001370'],
 ['FUR-CH-10002024'],
 ['OFF-AR-10001315', 'OFF-AP-10002118', 'OFF-PA-10002137'],
 ['FUR-CH-10002439'],
 ['TEC-CO-10001449'],
 ['FUR-FU-10003829'],
 ['OFF-PA-10002005', 'OFF-FA-10002815'],
 ['OFF-AR-10003504', 'OFF-LA-10000305'],
 ['FUR-FU-10001196', 'TEC-AC-10002942'],
 ['OFF-PA-10004888', 'OFF-ST-10000736', 'OFF-BI-10001120', 'OFF-BI-10000301'],
 ['OFF-AR-10002067', 'FUR-CH-10001215', 'FUR-TA-10004175'],
 ['OFF-AR-10001374'],
 ['OFF-PA-10004519'],
 ['OFF-LA-10000240', 'FUR-FU-10000629', 'OFF-AP-10001005', 'OFF-PA-10002377'],
 ['FUR-FU-10000222'],
 ['OFF-AR-10003190', 'FUR-CH-10000155', 'OFF-ST-10003058', 'FUR-TA-10004767'],
 ['OFF-BI-10000050'],
 ['OFF-BI-10003925', 'TEC-PH-10001530'],
 ['OFF-BI-10001294'],
 ['FUR-TA-10001039', 'OFF-BI-10000474', 'FUR-CH-10004698', 'OFF-ST-10003327'],
 ['OFF-PA-10002947', 'OFF-BI-10003476'],
 ['FUR-FU-10002111'],
 ['TEC-PH-10000376'],
 ['OFF-AP-10001154',
  'OFF-PA-10000466',
  'OFF-AR-10003829',
  'OFF-BI-10001758',
  'OFF-BI-10000136'],
 ['OFF-PA-10000659', 'OFF-PA-10001144', 'FUR-CH-10003817'],
 ['OFF-BI-10001628', 'OFF-ST-10000877', 'OFF-AR-10004752', 'OFF-LA-10000452'],
 ['OFF-FA-10003021'],
 ['TEC-PH-10004188', 'FUR-BO-10004015', 'OFF-ST-10000991'],
 ['OFF-ST-10003470', 'FUR-BO-10003159'],
 ['OFF-PA-10003036', 'OFF-BI-10002026'],
 ['OFF-ST-10002011', 'FUR-FU-10002379', 'OFF-AR-10003752'],
 ['FUR-FU-10001546'],
 ['OFF-BI-10000546'],
 ['OFF-PA-10003823'],
 ['OFF-PA-10001977', 'OFF-AP-10000692'],
 ['OFF-LA-10004425'],
 ['OFF-AP-10001293', 'OFF-ST-10004258', 'OFF-ST-10002214', 'OFF-BI-10004970'],
 ['FUR-BO-10004218', 'TEC-PH-10002185'],
 ['OFF-SU-10004661'],
 ['FUR-CH-10001854', 'OFF-AR-10000475'],
 ['FUR-FU-10001940', 'OFF-AP-10004336', 'TEC-AC-10003709'],
 ['TEC-AC-10004171'],
 ['OFF-BI-10001191', 'OFF-SU-10004115', 'FUR-CH-10000513'],
 ['OFF-FA-10002676',
  'FUR-FU-10000758',
  'OFF-LA-10002271',
  'OFF-BI-10002609',
  'OFF-FA-10000254'],
 ['OFF-ST-10000585', 'TEC-PH-10003484'],
 ['OFF-AP-10001563', 'TEC-AC-10004510'],
 ['FUR-FU-10001588'],
 ['OFF-AR-10001149',
  'OFF-PA-10000130',
  'OFF-PA-10002479',
  'FUR-CH-10004997',
  'OFF-ST-10004950',
  'OFF-ST-10001490'],
 ['OFF-BI-10003676'],
 ['OFF-FA-10000585', 'OFF-AP-10004859'],
 ['TEC-PH-10000984', 'OFF-BI-10000666', 'OFF-BI-10003712'],
 ['TEC-MA-10004679'],
 ['OFF-BI-10003684'],
 ['OFF-AR-10004930'],
 ['TEC-AC-10000736', 'OFF-AP-10001293', 'OFF-SU-10000157'],
 ['FUR-TA-10004442'],
 ['OFF-EN-10004773', 'OFF-BI-10004970'],
 ['FUR-FU-10002045'],
 ['OFF-AR-10000122', 'OFF-BI-10003656', 'OFF-FA-10002780', 'TEC-PH-10000702'],
 ['OFF-BI-10002012', 'OFF-AP-10001303'],
 ['FUR-FU-10001095'],
 ['OFF-AR-10004757'],
 ['TEC-PH-10003811'],
 ['OFF-ST-10002344', 'TEC-PH-10003589', 'FUR-FU-10000758', 'TEC-MA-10004679'],
 ['OFF-AR-10003469',
  'FUR-TA-10004175',
  'OFF-LA-10002945',
  'OFF-PA-10000533',
  'OFF-ST-10004459',
  'FUR-TA-10004147'],
 ['OFF-AR-10004582'],
 ['OFF-AP-10001962'],
 ['TEC-PH-10000895', 'OFF-PA-10000552'],
 ['OFF-AR-10002804'],
 ['TEC-AC-10002323'],
 ['FUR-CH-10002372'],
 ['OFF-BI-10002764'],
 ['OFF-BI-10003684'],
 ['OFF-ST-10001713'],
 ['OFF-BI-10000666', 'TEC-PH-10002890'],
 ['OFF-AP-10000692'],
 ['OFF-BI-10000632', 'OFF-EN-10004773'],
 ['TEC-PH-10000215'],
 ['OFF-AR-10002952'],
 ['FUR-FU-10004415'],
 ['FUR-FU-10002553', 'OFF-BI-10002103'],
 ['FUR-CH-10001854'],
 ['OFF-BI-10003676', 'TEC-AC-10001314'],
 ['FUR-TA-10002607', 'OFF-ST-10001809'],
 ['OFF-AP-10000576'],
 ['TEC-CO-10001571',
  'OFF-AP-10002495',
  'OFF-EN-10002500',
  'FUR-FU-10002088',
  'TEC-PH-10001128'],
 ['OFF-AR-10002956'],
 ['TEC-CO-10004202'],
 ['OFF-ST-10001097', 'OFF-ST-10001469'],
 ['TEC-PH-10000455', 'FUR-FU-10002456', 'FUR-TA-10003569'],
 ['FUR-FU-10003553', 'FUR-TA-10003008'],
 ['TEC-AC-10002842'],
 ['FUR-TA-10001307'],
 ['TEC-PH-10002170',
  'OFF-BI-10001078',
  'OFF-BI-10001031',
  'OFF-LA-10001158',
  'OFF-LA-10001613'],
 ['OFF-PA-10001837',
  'OFF-SU-10004661',
  'FUR-FU-10003274',
  'TEC-PH-10000149',
  'OFF-PA-10000019',
  'OFF-PA-10001125'],
 ['OFF-PA-10001526', 'TEC-AC-10002857'],
 ['OFF-ST-10002615', 'FUR-FU-10000521', 'OFF-LA-10000121', 'OFF-PA-10001289'],
 ['OFF-PA-10001457', 'OFF-PA-10001804'],
 ['FUR-CH-10002439'],
 ['OFF-LA-10001175'],
 ['OFF-AP-10000358', 'OFF-AP-10003281', 'OFF-PA-10000029'],
 ['OFF-EN-10000056', 'OFF-ST-10001469'],
 ['TEC-PH-10001079', 'OFF-BI-10003460'],
 ['OFF-PA-10001019', 'OFF-SU-10002537', 'OFF-ST-10003221'],
 ['OFF-PA-10001752'],
 ['OFF-EN-10003072', 'FUR-CH-10003973'],
 ['FUR-FU-10002111'],
 ['TEC-PH-10001079',
  'FUR-TA-10002041',
  'OFF-BI-10001036',
  'OFF-PA-10000223',
  'TEC-MA-10003246'],
 ['TEC-PH-10003484',
  'FUR-CH-10001394',
  'FUR-BO-10002213',
  'OFF-LA-10002762',
  'OFF-AP-10003842',
  'TEC-PH-10003072'],
 ['TEC-AC-10000158'],
 ['OFF-FA-10000936', 'OFF-BI-10001249', 'OFF-BI-10004632'],
 ['OFF-BI-10002133', 'OFF-BI-10002225'],
 ['OFF-BI-10004022'],
 ['OFF-PA-10000223'],
 ['OFF-AP-10003590',
  'OFF-PA-10000806',
  'OFF-AR-10000896',
  'TEC-PH-10002310',
  'OFF-ST-10002289',
  'OFF-BI-10002852'],
 ['OFF-PA-10001144', 'FUR-CH-10003761', 'OFF-PA-10004665', 'OFF-ST-10000078'],
 ['OFF-PA-10004610'],
 ['OFF-AR-10004042'],
 ['FUR-FU-10001706', 'FUR-TA-10002958'],
 ['TEC-PH-10001363', 'FUR-CH-10003312', 'FUR-FU-10004018', 'TEC-AC-10004814'],
 ['FUR-FU-10000193'],
 ['OFF-PA-10000533'],
 ['OFF-PA-10001952'],
 ['FUR-FU-10003691', 'OFF-AR-10003903', 'OFF-FA-10004854'],
 ['OFF-BI-10004656', 'OFF-ST-10002344', 'OFF-PA-10001800', 'OFF-ST-10000036'],
 ['FUR-FU-10000010'],
 ['OFF-EN-10003134', 'FUR-CH-10003396', 'OFF-PA-10001560', 'OFF-BI-10000977'],
 ['TEC-PH-10000673'],
 ['OFF-ST-10003722', 'TEC-MA-10001127'],
 ['OFF-EN-10004773'],
 ['TEC-AC-10001635',
  'OFF-LA-10001317',
  'FUR-TA-10000577',
  'OFF-LA-10000248',
  'OFF-PA-10000955',
  'FUR-FU-10000221'],
 ['OFF-LA-10001613'],
 ['OFF-AP-10004249'],
 ['FUR-FU-10002505', 'TEC-AC-10003832', 'OFF-SU-10002537'],
 ['OFF-ST-10002615'],
 ['TEC-AC-10001432', 'FUR-TA-10003715', 'OFF-BI-10003291'],
 ['OFF-AR-10002053', 'TEC-AC-10002567'],
 ['OFF-PA-10003641'],
 ['TEC-AC-10000023', 'OFF-PA-10003971', 'OFF-AR-10003481', 'OFF-ST-10001490'],
 ['OFF-AR-10002445'],
 ['TEC-PH-10004700', 'OFF-BI-10004593', 'OFF-BI-10003429'],
 ['OFF-BI-10004390', 'OFF-AP-10002765'],
 ['OFF-PA-10001583'],
 ['TEC-PH-10004539', 'OFF-AR-10001919'],
 ['OFF-BI-10001359', 'FUR-BO-10002213'],
 ['OFF-AR-10003829', 'OFF-AR-10003338', 'TEC-AC-10002558', 'OFF-AR-10000034'],
 ['OFF-AP-10002892', 'TEC-AC-10002718', 'OFF-BI-10003527'],
 ['OFF-EN-10001219'],
 ['OFF-SU-10001574'],
 ['OFF-FA-10002280', 'TEC-MA-10000029'],
 ['TEC-PH-10003273', 'OFF-PA-10000100'],
 ['OFF-EN-10003001'],
 ['OFF-PA-10001289'],
 ['OFF-EN-10004955', 'OFF-BI-10001071', 'OFF-EN-10001990', 'OFF-AP-10002734'],
 ['TEC-PH-10001299', 'TEC-PH-10001552', 'OFF-BI-10001098'],
 ['OFF-PA-10001639'],
 ['OFF-AP-10000124', 'OFF-EN-10003567', 'FUR-CH-10004997', 'OFF-BI-10000494'],
 ['OFF-LA-10001569',
  'OFF-BI-10001132',
  'TEC-PH-10003095',
  'OFF-SU-10000432',
  'TEC-AC-10004227',
  'OFF-LA-10004409',
  'OFF-PA-10001569',
  'OFF-ST-10001031'],
 ['OFF-PA-10002893'],
 ['OFF-BI-10004970'],
 ['OFF-BI-10003314', 'FUR-TA-10004575'],
 ['FUR-CH-10003774'],
 ['FUR-FU-10000010'],
 ['OFF-SU-10004737'],
 ['OFF-LA-10002195'],
 ['OFF-AP-10002534'],
 ['FUR-CH-10002965', 'OFF-BI-10001636', 'OFF-AR-10004027'],
 ['FUR-FU-10001487', 'OFF-LA-10001934'],
 ['OFF-BI-10002353'],
 ['OFF-PA-10003883', 'TEC-PH-10003963', 'OFF-AP-10001303'],
 ['FUR-FU-10003489', 'OFF-PA-10000289', 'TEC-AC-10004227', 'OFF-ST-10000636'],
 ['OFF-BI-10002706'],
 ['OFF-PA-10002005'],
 ['OFF-EN-10002600'],
 ['OFF-SU-10003936'],
 ['OFF-AR-10003651'],
 ['FUR-FU-10004270',
  'OFF-BI-10000948',
  'OFF-PA-10000223',
  'FUR-FU-10004665',
  'TEC-PH-10000215'],
 ['OFF-FA-10004395', 'FUR-CH-10001270', 'FUR-FU-10001095', 'OFF-ST-10001469'],
 ['FUR-FU-10001861'],
 ['FUR-BO-10001337'],
 ['FUR-CH-10001797', 'OFF-BI-10003094'],
 ['TEC-PH-10001459'],
 ['OFF-AP-10004708', 'TEC-CO-10004115', 'TEC-PH-10002398', 'FUR-FU-10001979'],
 ['TEC-PH-10001644'],
 ['OFF-FA-10000621', 'FUR-FU-10003623', 'OFF-EN-10000781'],
 ['OFF-AP-10004136', 'OFF-BI-10003429'],
 ['OFF-LA-10002787', 'TEC-PH-10003645', 'TEC-PH-10001615'],
 ['FUR-CH-10004063',
  'OFF-ST-10002276',
  'OFF-PA-10004082',
  'OFF-AP-10002945',
  'OFF-PA-10000061'],
 ['OFF-AR-10001473',
  'OFF-AR-10000411',
  'OFF-PA-10000246',
  'TEC-MA-10004086',
  'OFF-PA-10003039',
  'TEC-AC-10004633'],
 ['OFF-EN-10003160', 'TEC-AC-10001542', 'OFF-ST-10003641', 'OFF-BI-10002432'],
 ['OFF-BI-10000962'],
 ['FUR-CH-10000454', 'OFF-PA-10004888'],
 ['TEC-AC-10001383'],
 ['OFF-BI-10004099'],
 ['FUR-TA-10004534'],
 ['OFF-ST-10001321'],
 ['OFF-ST-10001228'],
 ['TEC-AC-10001267'],
 ['OFF-AP-10003278'],
 ['OFF-PA-10003543', 'TEC-AC-10004353'],
 ['TEC-AC-10000736'],
 ['FUR-FU-10000723', 'OFF-BI-10000632'],
 ['FUR-FU-10004020', 'OFF-AR-10001955'],
 ['OFF-AR-10002656'],
 ['OFF-PA-10001970', 'OFF-BI-10002954'],
 ['OFF-PA-10001800'],
 ['OFF-BI-10001553'],
 ['OFF-ST-10002957', 'OFF-LA-10002312'],
 ['OFF-AR-10003394'],
 ['OFF-PA-10003228',
  'OFF-PA-10002586',
  'TEC-AC-10002049',
  'FUR-BO-10000362',
  'FUR-CH-10004218'],
 ['TEC-AC-10002550'],
 ['FUR-TA-10004289', 'OFF-AP-10003622'],
 ['OFF-AP-10001366', 'OFF-BI-10001636'],
 ['TEC-PH-10000376', 'TEC-AC-10000303', 'OFF-AR-10001953'],
 ['OFF-BI-10001757', 'TEC-PH-10004875'],
 ['OFF-AR-10003045', 'OFF-PA-10001363', 'OFF-FA-10002280'],
 ['OFF-SU-10001225', 'OFF-AR-10003752'],
 ['FUR-FU-10001424'],
 ['OFF-PA-10001204', 'OFF-ST-10000991'],
 ['OFF-AP-10001271', 'OFF-PA-10004353', 'TEC-AC-10002473'],
 ['TEC-CO-10001046'],
 ['OFF-AR-10001897', 'TEC-PH-10001795'],
 ['OFF-AP-10004868', 'FUR-CH-10004287', 'OFF-PA-10002689'],
 ['FUR-TA-10001705', 'OFF-ST-10004634', 'FUR-TA-10004442'],
 ['OFF-BI-10000977'],
 ['TEC-AC-10001445'],
 ['TEC-AC-10000023', 'TEC-PH-10001750'],
 ['OFF-PA-10002245'],
 ['OFF-AR-10004078', 'TEC-AC-10001266'],
 ['OFF-PA-10001954', 'FUR-CH-10002602'],
 ['FUR-TA-10004086'],
 ['OFF-PA-10004475', 'OFF-PA-10003001'],
 ['OFF-BI-10004828', 'OFF-BI-10003981'],
 ['TEC-PH-10001552', 'TEC-AC-10004877'],
 ['OFF-LA-10000452'],
 ['OFF-ST-10002574'],
 ['FUR-FU-10004090', 'FUR-CH-10002602', 'TEC-AC-10001142', 'TEC-PH-10004977'],
 ['OFF-ST-10004337', 'FUR-TA-10001932', 'OFF-BI-10003982', 'FUR-TA-10000617'],
 ['FUR-CH-10000225'],
 ['OFF-BI-10003719'],
 ['FUR-FU-10001967'],
 ['TEC-AC-10001606',
  'OFF-ST-10003805',
  'OFF-PA-10002109',
  'OFF-BI-10000632',
  'OFF-LA-10003510'],
 ['FUR-TA-10001889'],
 ['OFF-BI-10003910'],
 ['TEC-AC-10004571'],
 ['OFF-SU-10000157'],
 ['OFF-PA-10004071'],
 ['OFF-BI-10003638'],
 ['TEC-AC-10004859'],
 ['OFF-PA-10000349', 'FUR-FU-10002456'],
 ['OFF-EN-10002500', 'TEC-CO-10001766'],
 ['FUR-TA-10004607'],
 ['OFF-BI-10002103'],
 ['OFF-AR-10002135', 'TEC-PH-10002583'],
 ['OFF-ST-10002444'],
 ['OFF-EN-10001539',
  'FUR-FU-10000550',
  'TEC-AC-10003628',
  'TEC-MA-10004521',
  'OFF-AP-10003860',
  'OFF-BI-10000069'],
 ['OFF-ST-10000636', 'OFF-BI-10000145'],
 ['TEC-AC-10002323'],
 ['OFF-EN-10001335', 'OFF-ST-10003479', 'OFF-PA-10003016'],
 ['OFF-PA-10003177'],
 ['OFF-PA-10001800', 'OFF-AP-10001469', 'TEC-AC-10002399'],
 ['FUR-FU-10001876',
  'TEC-AC-10003628',
  'FUR-CH-10004860',
  'OFF-PA-10000357',
  'OFF-PA-10003270'],
 ['OFF-PA-10004734', 'OFF-BI-10000145'],
 ['OFF-AR-10003190'],
 ['TEC-PH-10001835'],
 ['TEC-AC-10001013'],
 ['TEC-PH-10000486', 'TEC-AC-10001606'],
 ['OFF-BI-10002049'],
 ['OFF-AP-10004708'],
 ['OFF-AR-10002053', 'OFF-ST-10002370'],
 ['TEC-AC-10001553', 'OFF-BI-10000309'],

In [60]:
df_grouped = sales.groupby('Order_ID')['Product_ID'].apply(list).tolist()
df_grouped

[['TEC-PH-10002075'],
 ['FUR-TA-10003715', 'OFF-BI-10001597'],
 ['OFF-PA-10000176'],
 ['OFF-BI-10000343'],
 ['OFF-FA-10000611', 'OFF-PA-10004733']]

In [8]:
# Encode the product lists into a one-hot format
te = TransactionEncoder()
te_array = te.fit(df_grouped).transform(df_grouped)
df_encoded = pd.DataFrame(te_array, columns=te.columns_)
df_encoded

,FUR-BO-10000112,FUR-BO-10000330,FUR-BO-10000362,FUR-BO-10000468,FUR-BO-10000711,FUR-BO-10000780,FUR-BO-10001337,FUR-BO-10001519,FUR-BO-10001567,FUR-BO-10001601,...,TEC-PH-10004833,TEC-PH-10004875,TEC-PH-10004896,TEC-PH-10004897,TEC-PH-10004908,TEC-PH-10004912,TEC-PH-10004922,TEC-PH-10004924,TEC-PH-10004959,TEC-PH-10004977
0,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
1,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
2,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
3,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
4,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
4917,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
4918,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
4919,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
4920,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
4921,False,False,False,False,False,False,False,True,False,False,...,False,False,False,False,False,False,False,False,False,False

In [12]:
frequent_itemsets = apriori(df_encoded, min_support=0.0004, use_colnames=True)
frequent_itemsets = frequent_itemsets[frequent_itemsets['itemsets'].apply(lambda x: len(x) == 2)]
frequent_itemsets

       support                            itemsets
1766  0.000406  (OFF-BI-10003676, FUR-BO-10001972)
1767  0.000406  (FUR-BO-10002213, OFF-LA-10002762)
1768  0.000406  (OFF-AP-10001563, FUR-CH-10002017)
1769  0.000406  (FUR-CH-10003379, TEC-PH-10003885)
1770  0.000406  (OFF-BI-10000320, FUR-CH-10003846)
1771  0.000406  (FUR-FU-10000010, OFF-BI-10002824)
1772  0.000406  (OFF-BI-10000315, FUR-FU-10000023)
1773  0.000406  (FUR-FU-10003464, TEC-PH-10002496)
1774  0.000406  (FUR-FU-10003832, OFF-BI-10001359)
1775  0.000406  (FUR-FU-10004973, OFF-FA-10000936)
1776  0.000406  (FUR-TA-10001039, TEC-PH-10004447)
1777  0.000406  (FUR-TA-10002645, TEC-AC-10003033)
1778  0.000406  (TEC-PH-10003187, FUR-TA-10003569)
1779  0.000406  (OFF-PA-10002195, OFF-AP-10000938)
1780  0.000406  (OFF-AR-10000914, TEC-AC-10000057)
1781  0.000406  (OFF-AR-10001683, OFF-BI-10000474)
1782  0.000406  (OFF-LA-10004544, OFF-AR-10001919)
1783  0.000406  (OFF-SU-10000432, OFF-AR-10003183)
1784  0.000406  (OFF-BI-10002160, OFF-AR-10004999)
1785  0.000406  (OFF-BI-10000773, OFF-BI-10001543)
1786  0.000406  (OFF-BI-10001098, TEC-PH-10001552)
1787  0.000406  (OFF-BI-10001617, OFF-ST-10000736)
1788  0.000406  (OFF-BI-10004001, OFF-BI-10001634)
1789  0.000406  (TEC-PH-10002834, OFF-BI-10001658)
1790  0.000406  (OFF-BI-10002735, TEC-PH-10001448)
1791  0.000406  (TEC-PH-10000702, OFF-FA-10002780)
1792  0.000406  (TEC-PH-10002293, OFF-FA-10002780)
1793  0.000406  (TEC-AC-10003095, OFF-LA-10004093)
1794  0.000406  (OFF-ST-10004507, OFF-PA-10001667)
1795  0.000406  (OFF-PA-10004101, OFF-PA-10002005)
1796  0.000406  (OFF-ST-10002214, OFF-PA-10002262)
1797  0.000406  (TEC-CO-10004722, OFF-ST-10001558)
1798  0.000406  (TEC-AC-10002637, OFF-ST-10002554)
1799  0.000406  (TEC-AC-10003399, OFF-SU-10001574)
1800  0.000406  (TEC-AC-10002049, TEC-AC-10003628)
1801  0.000406  (TEC-AC-10002049, TEC-PH-10000702)

In [17]:
rules = association_rules(frequent_itemsets, metric="lift", min_threshold=0.0004, support_only=True, num_itemsets=len(df_grouped))
rules = rules.sort_values(by="confidence", ascending=False)
rules

,antecedents,consequents,antecedent support,consequent support,support,confidence,lift,representativity,leverage,conviction,zhangs_metric,jaccard,certainty,kulczynski
0,(OFF-BI-10003676),(FUR-BO-10001972),NaN,NaN,0.000406,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,(FUR-BO-10001972),(OFF-BI-10003676),NaN,NaN,0.000406,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,(FUR-BO-10002213),(OFF-LA-10002762),NaN,NaN,0.000406,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,(OFF-LA-10002762),(FUR-BO-10002213),NaN,NaN,0.000406,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,(OFF-AP-10001563),(FUR-CH-10002017),NaN,NaN,0.000406,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
67,(OFF-SU-10001574),(TEC-AC-10003399),NaN,NaN,0.000406,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
68,(TEC-AC-10002049),(TEC-AC-10003628),NaN,NaN,0.000406,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
69,(TEC-AC-10003628),(TEC-AC-10002049),NaN,NaN,0.000406,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
70,(TEC-AC-10002049),(TEC-PH-10000702),NaN,NaN,0.000406,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
71,(TEC-PH-10000702),(TEC-AC-10002049),NaN,NaN,0.000406,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

#### Long-tail analysis

In [43]:
product_customer_count = sales.groupby('Product_ID')['Customer_ID'].nunique()
total_customers = sales['Customer_ID'].nunique()
product_customer_percentage = (product_customer_count / total_customers) * 100
small_threshold = 1
small_percentage_products = product_customer_count[product_customer_count == small_threshold]
small_percentage_products

Product_ID
FUR-BO-10000112    1
FUR-BO-10001567    1
FUR-BO-10002206    1
FUR-CH-10002317    1
FUR-FU-10002379    1
                  ..
TEC-PH-10002817    1
TEC-PH-10003535    1
TEC-PH-10004241    1
TEC-PH-10004830    1
TEC-PH-10004875    1
Name: Customer_ID, Length: 95, dtype: int64

In [36]:
product_customer_count = sales.groupby('Product_ID')['Customer_ID'].nunique()
pr_sorted = product_customer_count.sort_values(ascending=False)
pr_sorted

Product_ID
TEC-AC-10003832    18
OFF-PA-10001970    18
FUR-FU-10004270    15
TEC-AC-10003628    15
FUR-CH-10001146    14
                   ..
OFF-AP-10000326     1
OFF-ST-10001414     1
FUR-TA-10001691     1
OFF-ST-10001034     1
FUR-BO-10000112     1
Name: Customer_ID, Length: 1861, dtype: int64

In [48]:
product_customer_count = sales.groupby('Product_ID')['Customer_ID'].nunique().reset_index()

# Step 2: Group by the number of customers and count how many products have been bought by that number of customers
customer_group_count = product_customer_count.groupby('Customer_ID')['Product_ID'].count().reset_index()

# Step 3: Rename columns for clarity
customer_group_count.columns = ['Number_of_Customers', 'Number_of_Products']
customer_group_count

    Number_of_Customers  Number_of_Products
0                     1                  95
1                     2                 181
2                     3                 219
3                     4                 294
4                     5                 300
5                     6                 240
6                     7                 189
7                     8                 155
8                     9                  73
9                    10                  48
10                   11                  28
11                   12                  16
12                   13                  11
13                   14                   8
14                   15                   2
15                   18                   2

#### Top-selling states

In [70]:
state_name_to_abbr = {
    'Alabama': 'AL', 'Alaska': 'AK', 'Arizona': 'AZ', 'Arkansas': 'AR',
    'California': 'CA', 'Colorado': 'CO', 'Connecticut': 'CT', 'Delaware': 'DE',
    'Florida': 'FL', 'Georgia': 'GA', 'Hawaii': 'HI', 'Idaho': 'ID',
    'Illinois': 'IL', 'Indiana': 'IN', 'Iowa': 'IA', 'Kansas': 'KS',
    'Kentucky': 'KY', 'Louisiana': 'LA', 'Maine': 'ME', 'Maryland': 'MD',
    'Massachusetts': 'MA', 'Michigan': 'MI', 'Minnesota': 'MN', 'Mississippi': 'MS',
    'Missouri': 'MO', 'Montana': 'MT', 'Nebraska': 'NE', 'Nevada': 'NV',
    'New Hampshire': 'NH', 'New Jersey': 'NJ', 'New Mexico': 'NM',
    'New York': 'NY', 'North Carolina': 'NC', 'North Dakota': 'ND',
    'Ohio': 'OH', 'Oklahoma': 'OK', 'Oregon': 'OR', 'Pennsylvania': 'PA',
    'Rhode Island': 'RI', 'South Carolina': 'SC', 'South Dakota': 'SD',
    'Tennessee': 'TN', 'Texas': 'TX', 'Utah': 'UT', 'Vermont': 'VT',
    'Virginia': 'VA', 'Washington': 'WA', 'West Virginia': 'WV',
    'Wisconsin': 'WI', 'Wyoming': 'WY'
}
sales['State'] = sales['State'].astype(str)
sales['State'] = sales['State'].map(state_name_to_abbr)
sales

,Order_ID,Order_Date,Ship_Date,Ship_Mode,Customer_ID,Customer_Name,Segment,Country,City,State,Region,Product_ID,Category,Sub_Category,Product_Name,Sales
0,CA-2017-152156,2017-11-08,2017-11-11,Second Class,CG-12520,Claire Gute,Consumer,United States,Henderson,KY,South,FUR-BO-10001798,Furniture,Bookcases,Bush Somerset Collection Bookcase,261.9600
1,CA-2017-152156,2017-11-08,2017-11-11,Second Class,CG-12520,Claire Gute,Consumer,United States,Henderson,KY,South,FUR-CH-10000454,Furniture,Chairs,"Hon Deluxe Fabric Upholstered Stacking Chairs,...",731.9400
2,CA-2017-138688,2017-06-12,2017-06-16,Second Class,DV-13045,Darrin Van Huff,Corporate,United States,Los Angeles,CA,West,OFF-LA-10000240,Office Supplies,Labels,Self-Adhesive Address Labels for Typewriters b...,14.6200
3,US-2016-108966,2016-10-11,2016-10-18,Standard Class,SO-20335,Sean O Donnel,Consumer,United States,Fort Lauderdale,FL,South,FUR-TA-10000577,Furniture,Tables,Bretford CR4500 Series Slim Rectangular Table,957.5775
4,US-2016-108966,2016-10-11,2016-10-18,Standard Class,SO-20335,Sean O Donnel,Consumer,United States,Fort Lauderdale,FL,South,OFF-ST-10000760,Office Supplies,Storage,Eldon Fold N Roll Cart System,22.3680
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
9795,CA-2017-125920,2017-05-21,2017-05-28,Standard Class,SH-19975,Sally Hughsby,Corporate,United States,Chicago,IL,Central,OFF-BI-10003429,Office Supplies,Binders,"Cardinal HOLDit! Binder Insert Strips,Extra St...",3.7980
9796,CA-2016-128608,2016-01-12,2016-01-17,Standard Class,CS-12490,Cindy Schnelling,Corporate,United States,Toledo,OH,East,OFF-AR-10001374,Office Supplies,Art,"BIC Brite Liner Highlighters, Chisel Tip",10.3680
9797,CA-2016-128608,2016-01-12,2016-01-17,Standard Class,CS-12490,Cindy Schnelling,Corporate,United States,Toledo,OH,East,TEC-PH-10004977,Technology,Phones,GE 30524EE4,235.1880
9798,CA-2016-128608,2016-01-12,2016-01-17,Standard Class,CS-12490,Cindy Schnelling,Corporate,United States,Toledo,OH,East,TEC-PH-10000912,Technology,Phones,Anker 24W Portable Micro USB Car Charger,26.3760
9799,CA-2016-128608,2016-01-12,2016-01-17,Standard Class,CS-12490,Cindy Schnelling,Corporate,United States,Toledo,OH,East,TEC-AC-10000487,Technology,Accessories,SanDisk Cruzer 4 GB USB Flash Drive,10.3840

In [71]:
states_grouped = sales.groupby('State')['Sales'].sum().reset_index()
states_sorted = states_grouped.sort_values(by='Sales',ascending=False)
states_sorted

   State        Sales
3     CA  446306.4635
31    NY  306361.1470
40    TX  168572.5322
44    WA  135206.8500
35    PA  116276.6500
7     FL   88436.5320
11    IL   79236.5170
19    MI   76136.0740
32    OH   75130.3500
42    VA   70636.7200
24    NC   55165.9640
12    IN   48718.4000
8     GA   48219.1100
14    KY   36458.3900
2     AZ   35272.6570
28    NJ   34610.9720
4     CO   31841.5980
45    WI   31173.4300
39    TN   30661.8730
20    MN   29863.1500
16    MA   28634.4340
6     DE   27322.9990
17    MD   23705.5230
36    RI   22525.0260
21    MO   22205.1500
33    OK   19683.3900
0     AL   19510.6400
34    OR   17284.4620
30    NV   16729.1020
5     CT   13384.3570
1     AR   11678.1300
41    UT   11220.0560
22    MS   10771.3400
15    LA    9131.0500
43    VT    8929.3700
37    SC    8481.7100
26    NE    7464.9300
27    NH    7292.5240
23    MT    5589.3520
29    NM    4783.5220
9     IA    4443.5600
10    ID    4382.4860
13    KS    2914.3100
47    WY    1603.1360
38    SD    1315.5600
18    ME    1270.5300
46    WV    1209.8240
25    ND     919.9100

In [72]:
state_sales = sales.groupby(['State', 'Region'])['Sales'].sum().reset_index()
state_sales

   State   Region        Sales
0     AL    South   19510.6400
1     AR    South   11678.1300
2     AZ     West   35272.6570
3     CA     West  446306.4635
4     CO     West   31841.5980
5     CT     East   13384.3570
6     DE     East   27322.9990
7     FL    South   88436.5320
8     GA    South   48219.1100
9     IA  Central    4443.5600
10    ID     West    4382.4860
11    IL  Central   79236.5170
12    IN  Central   48718.4000
13    KS  Central    2914.3100
14    KY    South   36458.3900
15    LA    South    9131.0500
16    MA     East   28634.4340
17    MD     East   23705.5230
18    ME     East    1270.5300
19    MI  Central   76136.0740
20    MN  Central   29863.1500
21    MO  Central   22205.1500
22    MS    South   10771.3400
23    MT     West    5589.3520
24    NC    South   55165.9640
25    ND  Central     919.9100
26    NE  Central    7464.9300
27    NH     East    7292.5240
28    NJ     East   34610.9720
29    NM     West    4783.5220
30    NV     West   16729.1020
31    NY     East  306361.1470
32    OH     East   75130.3500
33    OK  Central   19683.3900
34    OR     West   17284.4620
35    PA     East  116276.6500
36    RI     East   22525.0260
37    SC    South    8481.7100
38    SD  Central    1315.5600
39    TN    South   30661.8730
40    TX  Central  168572.5322
41    UT     West   11220.0560
42    VA    South   70636.7200
43    VT     East    8929.3700
44    WA     West  135206.8500
45    WI  Central   31173.4300
46    WV     East    1209.8240
47    WY     West    1603.1360

In [74]:
state_sales['State'].tolist()

['AL',
 'AR',
 'AZ',
 'CA',
 'CO',
 'CT',
 'DE',
 'FL',
 'GA',
 'IA',
 'ID',
 'IL',
 'IN',
 'KS',
 'KY',
 'LA',
 'MA',
 'MD',
 'ME',
 'MI',
 'MN',
 'MO',
 'MS',
 'MT',
 'NC',
 'ND',
 'NE',
 'NH',
 'NJ',
 'NM',
 'NV',
 'NY',
 'OH',
 'OK',
 'OR',
 'PA',
 'RI',
 'SC',
 'SD',
 'TN',
 'TX',
 'UT',
 'VA',
 'VT',
 'WA',
 'WI',
 'WV',
 'WY']

In [78]:

regional_sales =sales[sales['Region'] == 'West']
state_sales = regional_sales.groupby('State')['Sales'].sum().reset_index()
state_sales

   State        Sales
0     AZ   35272.6570
1     CA  446306.4635
2     CO   31841.5980
3     ID    4382.4860
4     MT    5589.3520
5     NM    4783.5220
6     NV   16729.1020
7     OR   17284.4620
8     UT   11220.0560
9     WA  135206.8500
10    WY    1603.1360

#### Operational insights